### PR TITLE
Fix square() argument handling

### LINKED ISSUE #4343: 1.0.0 broke syntax for square with rounded corners
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug: 

- p5.js version: 1.0.0
- Steps to reproduce this:

```
// with 0.10.2: 
  square(x, y, size, corner_radius);

// with 1.0.0:
  square(x, y, size, size, corner_radius);
```

### PR DESCRIPTION
**Pull request by AnuragGupta93**
Resolves #4343

 Changes:
* Fixed 1.0.0 broke syntax for square with rounded corners
* Corrected parameters passed from `p5.prototype.square` to `p5.prototype._renderRect`
* Removed redundant code for the square in `p5.prototype._renderRect`

 Screenshots of the change:
`square(30, 20, 55);`
image
`square(30, 20, 55, 20);`
image
`square(30, 20, 55, 20, 15, 10, 5);`
image
`rect(30, 20, 55, 55);`
image
`rect(30, 20, 55, 55, 20);`
image
`rect(30, 20, 55, 55, 20, 15, 10, 5);`
image

#### PR Checklist
- [x] Every function working correctly
- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/master/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/master/contributor_docs#unit-tests

### CODE REVIEW

File: src/core/shape/2d_primitives.js [hunk 1]
```diff
@@ -618,17 +618,16 @@ p5.prototype.rect = function() {
  */
 p5.prototype.square = function(x, y, s, tl, tr, br, bl) {
   p5._validateParameters('square', arguments);
-  return this._renderRect.apply(this, arguments);
+  // duplicate width for height as only one value given
+  let args = Array.prototype.slice.call(arguments, 0, 3);
+  args.push(arguments[2]);
+  args = args.concat(Array.prototype.slice.call(arguments, 4));
+  return this._renderRect.apply(this, args);
```
Comment (limzykenneth) [inline src/core/shape/2d_primitives.js]: Wouldn't it be easier to just do 
```
return this._renderRect(x, y, s, s, tl, tr, br, bl);
```
or if `apply` is preferred: 
```
return this._renderRect.apply(this, [x, y, s, s, tl, tr, br, bl]);
```

File: src/core/shape/2d_primitives.js [hunk 2]
```diff
@@ -618,17 +618,16 @@ p5.prototype.rect = function() {
...
 };
 
 // internal method to have renderer draw a rectangle
 p5.prototype._renderRect = function() {
   if (this._renderer._doStroke || this._renderer._doFill) {
-    // duplicate width for height if only one value given
-    if (arguments.length === 3) {
-      arguments[3] = arguments[2];
-    }
-
```
Comment (limzykenneth) [inline src/core/shape/2d_primitives.js]: This check is in place because `rect()` also takes a 3 argument overload which draws a square. It should be moved or something similar implemented in `rect()` itself.

Comment (AnuragGupta93) [reply src/core/shape/2d_primitives.js]: Oh, I thought to remove it because of the absence of example in the example section of `rect()` method with 3 arguments. Thought that it was done for overloading `square()`. 
So I guess after doing this, an example of rectangle with 3 arguments needed to be implemented in the docs.
What's your thought?

File: src/core/shape/2d_primitives.js (hunk 1 above)
Comment (AnuragGupta93) [reply src/core/shape/2d_primitives.js]: Done this to just insert an element in the third position but that might not be necessary. Correcting in a while.

File: src/core/shape/2d_primitives.js (hunk 2 above)
Comment (limzykenneth) [reply src/core/shape/2d_primitives.js]: @AnuragGupta93 I don't think an extra example for `rect()` with 3 arguments is necessary, the function signature should take care of it and an extra example is a bit much. But that's just me.

File: src/core/shape/2d_primitives.js [hunk 3]
```diff
@@ -618,17 +618,17 @@ p5.prototype.rect = function() {
...
-  return this._renderRect.apply(this, arguments);
+  // duplicate width for height in case of square
+  return this._renderRect.apply(this, [x, y, s, s, tl, tr, br, bl]);
 };
 
 // internal method to have renderer draw a rectangle
 p5.prototype._renderRect = function() {
   if (this._renderer._doStroke || this._renderer._doFill) {
-    // duplicate width for height if only one value given
+    // duplicate width for height in case only 3 arguments is provided
```
[the remark this answers is not in the document]
Comment (AnuragGupta93) [reply src/core/shape/2d_primitives.js]: By one value, I mean one side. But that's okay.

File: src/core/shape/2d_primitives.js [hunk 4]
```diff
@@ -618,17 +618,17 @@ p5.prototype.rect = function() {
  */
 p5.prototype.square = function(x, y, s, tl, tr, br, bl) {
   p5._validateParameters('square', arguments);
-  return this._renderRect.apply(this, arguments);
+  // duplicate width for height in case of square
+  return this._renderRect.apply(this, [x, y, s, s, tl, tr, br, bl]);
```
[the remark this answers is not in the document]
Comment (AnuragGupta93) [reply src/core/shape/2d_primitives.js]: Thanks for the advice @outofambit .

File: src/core/shape/2d_primitives.js (hunk 2 above)
Comment (AnuragGupta93) [reply src/core/shape/2d_primitives.js]: Agreed
