### PR TITLE
Made a new method to return Geometry with no internal colors.

### LINKED ISSUE #6384: Vertex colors don't save in buildGeometry() with a single color, but do when multiple colors used
*Edit from @davepagurek:*

- It is unclear how materials should work inside p5.Geometry: some material properties (vertex colors) are included (and only sometimes; they are discarded if they are all the same), and others never are (e.g. specular material)
- To fix this:
  - We should define clearly what properties are included in p5.Geometry
  - To be more consistent, we should likely include all materials or no materials, and be explicit about which
  - This probably means making a wrapper around p5.Geometry that also includes materials
  - This probably means having a method to turn the above into a materilalless p5.Geometry

*Original bug report:*

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [X] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.7.0.0

### Web browser and version

Chrome

### Operating System

MacOSX

### Steps to reproduce this

Hi all!,

I'm using the new geometry feature from this push https://github.com/processing/p5.js/pull/6287 , However I am having problems creating geometries with transparency, I would expect that using the function `fill()` with alpha would generate a triangle with opacity, but the `beginGeometry() `and  `endGeometry()` ignore the transparent component. 
Am I doing something work?

```
let shape01;
let shape02;

let points = [];

function setup() {
  renderer = createCanvas(600, 600, WEBGL);
  
  points.push(new p5.Vector(-1, -1, 0));
  points.push(new p5.Vector(-1, 1, 0));
  points.push(new p5.Vector(1, -1, 0));
  points.push(new p5.Vector(-1, -1, 0));

  buildShape01();
  buildShape02();
}

function draw() {
  background(0);

  model(shape01);  
  model(shape02);
}

function buildShape01() {
  beginGeometry();
  fill(255, 0, 0, 50);
  beginShape();

  for (let vec of points) {
    vertex(vec.x*100, vec.y*100, vec.z*100);
  }
  endShape(CLOSE);
  shape01 = endGeometry();
}

function buildShape02() {
  beginGeometry();
  fill(0, 255, 0, 150);
  beginShape();
  for (let vec of points) {
    vertex(vec.x*200, vec.y*200, vec.z*200);
  }
  endShape(CLOSE);
  shape02 = endGeometry();
}
```
https://editor.p5js.org/thomaslengeling/sketches/a6-7PZ9IR

Many Thanks!

### PR DESCRIPTION
**Pull request by perminder-17**
Resolves #6384 

 Changes:

https://github.com/processing/p5.js/assets/127239756/36d5714b-d94c-4e21-9e31-82ef2047204a

Description:

let shap01;
function setup() {
  renderer = createCanvas(600, 600, WEBGL);
  buildShape02();
}
function draw() {
  background(0);
  fill("yellow");
  model(shape02);
}

function buildShape02() {
  beginGeometry();
  fill("red"); //The box is red
  box(50);
  shape02 = endGeometry();
  shape02.clearColors(); //After calling this the box becomes yellow as it removes internal colors.
}

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

File: src/webgl/3d_primitives.js [hunk 1]
```diff
@@ -180,6 +180,14 @@ p5.prototype.freeGeometry = function(geometry) {
   this._renderer._freeBuffers(geometry.gid);
 };
 
+/**
+ * Clears the internal Color of the Geometry.
+ * @method clearColors
+ */
+p5.prototype.clearColors = function () {
```
Comment (davepagurek) [inline src/webgl/3d_primitives.js:187]: I think maybe we can take out this method now that we have one on `p5.Geometry`.

File: src/webgl/p5.Geometry.js [hunk 2]
```diff
@@ -88,6 +88,10 @@ p5.Geometry = class Geometry {
     this.dirtyFlags = {};
   }
 
+  clearColors() {
```
Comment (davepagurek) [inline src/webgl/p5.Geometry.js:91]: Do you think you can add a doc comment around this one? It would be nice to add your example in the video in your PR description. Maybe we can add two examples: one showing the behaviour without `clearColors()`, and one showing the behaviour with `clearColors()`?

Here's an example of a doc comment with an example sketch on another class. Adding one here would look similar: https://github.com/processing/p5.js/blob/716554fd780f28390dbcfdcf4ac85304750d8211/src/webgl/p5.Framebuffer.js#L750-L794

**Review by davepagurek — COMMENTED** [review]
Nice work on this! I think we just want to add some documentation to the new method now.

File: src/webgl/p5.Geometry.js (hunk 2 above)
Comment (perminder-17) [reply src/webgl/p5.Geometry.js:91]: Okay, I will add a doc comment around this one.

File: src/webgl/3d_primitives.js (hunk 1 above)
Comment (perminder-17) [reply src/webgl/3d_primitives.js:187]: Okay

**Comment by perminder-17** [comment]
@davepagurek , I have added a doc comment with two examples. Can you check and suggest what else we need?

File: src/webgl/p5.Geometry.js [hunk 3]
```diff
@@ -87,7 +87,59 @@ p5.Geometry = class Geometry {
...
+   * }
+   *
+   * function buildShape02() {
+   *   beginGeometry();
+   *   fill('red');  // shape02.clearColors() removes its internal colors. Now, shape02 is red.
+   *   beginShape();
+   *   for (let vec of points) vertex(vec.x * 200, vec.y * 200, vec.z * 200);
+   *   endShape(CLOSE);
+   *   shape02 = endGeometry();
+   *   // You can also call shape02.clearColors() here.
```
Comment (davepagurek) [inline src/webgl/p5.Geometry.js:134]: How do you feel about putting the `clearColors()` here? It also works having it in `draw`, but it only needs to be called once, so it feels like only doing it once when building the shape fits more cleanly.

File: src/webgl/p5.Geometry.js [hunk 4]
```diff
@@ -87,7 +87,59 @@ p5.Geometry = class Geometry {
...
+   *
+   * @example
+   * <div>
+   * <code>
+   * let shape01;
+   * let shape02;
+   * let points = [];
+   *
+   * function setup() {
+   *   renderer = createCanvas(600, 600, WEBGL);
```
Comment (davepagurek) [inline src/webgl/p5.Geometry.js:103]: I think we can take out the `renderer =` because we don't use it elsewhere.

File: src/webgl/p5.Geometry.js [hunk 5]
```diff
@@ -87,7 +87,59 @@ p5.Geometry = class Geometry {
 
     this.dirtyFlags = {};
   }
-
+  /**
+   * Removes the internal Colors of p5.Geometry
```
Comment (davepagurek) [inline src/webgl/p5.Geometry.js:91]: Maybe we can add one more sentence after this explaining that this lets you supply new colors with `fill()` before drawing it? And otherwise, `fill()` gets ignored?

**Review by davepagurek — COMMENTED** [review]
Nice work so far, and great comments in the example! I just have a few more comments to clean up the example a bit.

File: src/webgl/p5.Geometry.js (hunk 5 above)
Comment (perminder-17) [reply src/webgl/p5.Geometry.js:91]: Yes. I was also thinking of that... Okay going to add this.

File: src/webgl/p5.Geometry.js (hunk 4 above)
Comment (perminder-17) [reply src/webgl/p5.Geometry.js:103]: Oh yess... I will take out that.

File: src/webgl/p5.Geometry.js (hunk 5 above)
Comment (davepagurek) [reply src/webgl/p5.Geometry.js:91]: One other small request: could we add a period at the end of the sentence so it fits with the style of the next bit of text? other than that I think everything looks good!

File: src/webgl/p5.Geometry.js [hunk 6]
```diff
@@ -90,7 +90,7 @@ p5.Geometry = class Geometry {
   /**
    * Removes the internal Colors of p5.Geometry
    * Using clearColors, you can use 'fill()' to supply new colors before drawing each shape.
-   * If clearColors() is not used, the shapes will use their internal colors.
+   * If clearColors() is not used, the shapes will use their internal colors by ignoring 'fill()'.
```
Comment (davepagurek) [inline src/webgl/p5.Geometry.js:93]: If you use backticks around the function names, they'll get rendered like code:
```markdown
by ignoring `fill()`.
```
...becomes:

by ignoring `fill()`.

Comment (perminder-17) [reply src/webgl/p5.Geometry.js:93]: Okay...gonna do it.

File: src/webgl/p5.Geometry.js (hunk 5 above)
Comment (perminder-17) [reply src/webgl/p5.Geometry.js:91]: You mean fullstop?

**Comment by perminder-17** [comment]
@davepagurek Does it looks good now?

**Comment by perminder-17** [comment]
Any other change you want @davepagurek ?

File: src/webgl/p5.Geometry.js [hunk 7]
```diff
@@ -87,7 +87,60 @@ p5.Geometry = class Geometry {
 
     this.dirtyFlags = {};
   }
-
+  /**
+   * Removes the internal Colors of p5.Geometry.
```
Comment (davepagurek) [inline src/webgl/p5.Geometry.js:91]: oh also, we have an extra capital in here:
```suggestion
   * Removes the internal colors of p5.Geometry.
```

**Review by davepagurek — COMMENTED** [review]
Found two tiny things, and after that we're good to merge!

File: src/webgl/p5.Geometry.js (hunk 7 above)
Comment (perminder-17) [reply src/webgl/p5.Geometry.js:91]: Ok gonna do ASAP, wait

Comment (perminder-17) [reply src/webgl/p5.Geometry.js:91]: Btw nice observation 😅

**Review by davepagurek — APPROVED** [review]
Everything looks good to go now, thanks! 😁

**Comment by perminder-17** [comment]
Sorry @davepagurek for these all mistakes. And thankyou so much for the constant support.

**Comment by davepagurek** [comment]
No worries! Don't think of it so much as finding mistakes, rather it's just always helpful having an editor/reviewer to catch things that slip by. Hopefully it relieves some of the pressure knowing you don't have to get everything right yourself the first time because someone else is also helping to check!

**Comment by perminder-17** [comment]
> No worries! Don't think of it so much as finding mistakes, rather it's just always helpful having an editor/reviewer to catch things that slip by. Hopefully it relieves some of the pressure knowing you don't have to get everything right yourself the first time because someone else is also helping to check!

Yes, Thankyou so much. Love to contribute more like this.
