### PR TITLE
Better friendly error help for using p5 globals in top-level code.

### LINKED ISSUE #1247: Add more friendly error help for global APIs used at top-level code
In #1130 we added some logic that attempts to notice when people use p5's global APIs in top-level code, but it looks like there are some ways to improve it:

* Based on #1237 it looks like we might want to detect if `createGraphics` was called. Perhaps also the other p5 methods that start with `create`, e.g. `createCanvas`?
* Based on #903 it looks like folks will (understandably) expect P5's global constants to be defined during page load, so detecting for those would be good too.
* When @limzykenneth responded to #1237 he linked to a [helpful FAQ question](https://github.com/processing/p5.js/wiki/Frequently-Asked-Questions#why-cant-i-assign-variables-using-p5-functions-and-variables-before-setup), which would be nice for the friendly error logger to link to.

Another possibility for the first two is to actually embed an entire (auto-generated) list of every single public p5 symbol in the debug builds of p5.js, and match any pre-load exceptions thrown to it. This might have the downside of matching on *too many* exceptions, but it's also much more likely to help beginners... Hmm.

### PR DESCRIPTION
**Pull request by toolness**
This fixes #1247 by doing the following:

* Adding *everything* on `p5.prototype` (including constants like `PI`) on to the list of symbol names to search for in thrown error messages during page load. This should help with issues like #1237 and #903, and it will also help with some code that uses p5 addons too, e.g. using p5.dom's `select()` in top-level code. This might result in more false positives than are helpful, but maybe we should wait for bug reports to come in before deciding that?
* In the friendly error message, add a link to the helpful FAQ question [Why can't I assign variables using p5 functions and variables before `setup()`?](https://github.com/processing/p5.js/wiki/Frequently-Asked-Questions#why-cant-i-assign-variables-using-p5-functions-and-variables-before-setup) so users can get more details.
* Using more concise language to help the user, e.g.:
  * `Did you just try to use p5.js's HALF_PI constant?`
  * `Did you just try to use p5.js's random() function?`
  * `Did you just try to use p5.js's mouseX variable?`

Since this functionality is no longer really trivial, I also added a simple unit test suite.

I also added a bunch of comments in the code to explain some of the implementation decisions, as well as potential future workarounds.

### CODE REVIEW

File: src/core/error_helpers.js [hunk 1]
```diff
@@ -265,28 +265,111 @@ function friendlyWelcome() {
...
+      return {name: name, type: type};
+    });
+  };
+
+  misusedAtTopLevelCode = [].concat(
+    getSymbols(p5.prototype),
+    // At present, p5 only adds its constants to p5.prototype during
+    // construction, which may not have happened at the time a
+    // ReferenceError is thrown, so we'll manually add them to our list.
+    getSymbols(require('./constants'))
```
Comment (toolness) [inline src/core/error_helpers.js]: I was actually kind of surprised that the constants like `PI` aren't added to `p5.prototype` until `p5`'s constructor. Was this intentional?

It's particularly odd to me because [the comment in `core.js`](https://github.com/processing/p5.js/blob/f1335ba8e65ea391712ff060ffe5c7ee850ba9b9/src/core/core.js#L443-L446) says `// attach constants to p5 instance`, yet the code is actually adding the constants to `p5.prototype`, which is part of the class, rather than the instance. I could file a separate bug for this if needed.

File: test/test.html [hunk 2]
```diff
@@ -38,6 +38,7 @@
   <script src="unit/core/core.js" type="text/javascript" ></script>
   <!--<script src="unit/core/2d_primitives.js" type="text/javascript" ></script>-->
   <script src="unit/core/curves.js" type="text/javascript" ></script>
+  <script src="unit/core/error_helpers.js" type="text/javascript" ></script>
```
Comment (toolness) [inline test/test.html]: Note that I'm not adding this suite to `test-minified.html` because the friendly error help isn't supposed to be part of minified (optimized) builds.

File: src/core/error_helpers.js (hunk 1 above)
Comment (lmccart) [inline src/core/error_helpers.js]: I don't think there is a real reason for this, I have a feeling it's legacy code that hasn't been properly cleaned up. Please feel free to open an issue for this.

**Comment by lmccart** [comment]
this is great!
