### PR TITLE
fix: saveGif's third argument made more optional

### LINKED ISSUE #5927: make saveGif's third argument even more optional
### Increasing Access

maybe a bit of a stretch, but: improving/streamlining APIs makes them more accessible to folks who may not yet have the experience to understand what the error messages are saying and how to resolve them

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [X] Friendly Errors
- [ ] Other (specify if possible)

### Feature enhancement details

`saveGif` currently accepts an optional third argument in the form of an object with `delay` and `unit` keys. If you pass that object with only one of those keys defined (e.g. if you're trying to override delay but leave units alone, or vice versa) then you get an error message complaining about the format of the key you _didn't_ pass:

```
saveGif("loop.gif", 600, {"delay": 40})
=> TypeError: Units parameter must be either "frames" or "seconds"

saveGif("loop.gif", 600, {"unit": "seconds"})
=> TypeError: Delay parameter must be a number
```

In the first example I'm passing the `delay` key but getting an error message about units. In the second, passing `unit` but getting an error about delay.

The docs state that the default value for `unit` is seconds. The default for `delay` is not documented but the code shows it to be 0. Since both keys have defaults, I propose altering that function so that it will accept an object with only one of the keys defined.

### PR DESCRIPTION
**Pull request by Neilblaze**
`saveGif` currently accepts an optional third argument in the form of an object with delay and unit keys. If an object is passed with only one of those keys defined, then it returns an error message respectively.

#### Changes:

- Made optional third argument of `saveGif` even more optional.
- Checks are now performed on `delay` and `units` rather than `options.delay` and `options.units`

#### PR Checklist

- [ ] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

Thanks for the assist @davepagurek 🙌

### CODE REVIEW

**Review by Neilblaze — COMMENTED** [review]
My bad 😓 
I think it'll be this ⬇️ (You've mistakenly added semicolons after comments) 😅 

```js
const delay = (options && options.delay) || 0;  // in seconds
const units = (options && options.units) || 'seconds';  // either 'seconds' or 'frames'
```

Thanks for the catch @Qianqianye 💙

File: src/image/loading_displaying.js [hunk 1]
```diff
@@ -238,18 +238,10 @@ p5.prototype.saveGif = async function(
   if (typeof duration !== 'number') {
     throw TypeError('Duration parameter must be a number');
   }
-  // if arguments in the options object are not correct, cancel operation
-  if (typeof options.delay !== 'number') {
```
Comment (davepagurek) [inline src/image/loading_displaying.js:242]: How do you feel about putting these two checks back in, but checking `delay` and `units` rather than `options.delay` and `options.units`? That way, if one accidentally specifies units as, for example, 's' instead of 'seconds', they'll still hit an error. It will mean moving it to after we define those variables, I believe.

**Review by davepagurek — COMMENTED** [review]
Thanks for taking on this task! Just one comment about keeping our input checking around.

File: src/image/loading_displaying.js (hunk 1 above)
Comment (Neilblaze) [reply src/image/loading_displaying.js:242]: Yeah, that should be good! I'm on it.

File: src/image/loading_displaying.js [hunk 2]
```diff
@@ -238,19 +238,20 @@ p5.prototype.saveGif = async function(
...
     throw TypeError('Duration parameter must be a number');
   }
+
+  // extract variables for more comfortable use
+  const delay = (options && options.delay) || 0;  // in seconds
+  const units = (options && options.units) || 'seconds';  // either 'seconds' or 'frames'
+
   // if arguments in the options object are not correct, cancel operation
-  if (typeof options.delay !== 'number') {
+  if (typeof delay !== 'number' && delay !== null) {
```
Comment (davepagurek) [inline src/image/loading_displaying.js:247]: Looks good! Just for my understanding, was there a case that wasn't being handled that the `&& delay !== null` is needed for?

**Review by davepagurek — APPROVED** [review]
Thanks for making this change!

**Comment by Qianqianye** [comment]
Thank you both @Neilblaze and @davepagurek. I restarted the check process, and it's all passed. Ready to merge this PR if it looks good to you both.

File: src/image/loading_displaying.js (hunk 1 above)
Comment (wuyudi) [reply src/image/loading_displaying.js:242]:
```js
const delay = options?.delay ?? 0
const units = options?.units ?? 'seconds';
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing
😉

**Comment by davepagurek** [comment]
Thanks @Qianqianye!
