### PR TITLE
Fixed renderer getting out of sync

### LINKED ISSUE #3265: webgl: setAttributes() breaks resizeCanvas aspect
new in 0.7.2 (doesn't repro in 0.7.1)

- https://codepen.io/Spongman/pen/KGmNrB?editors=1010
- resize the window
- notice the circle is stretched

calling `setAttributes()` causes `resizeCanvas()` to *not* set the aspect ratio of the canvas correctly.

```javascript
function setup() {
  createCanvas(windowWidth, windowHeight, WEBGL);
  setAttributes('foobar', true);
}

function windowResized() {
  resizeCanvas(windowWidth, windowHeight);
}

function draw() {
  background(0);
  ellipse(0, 0, width/4);
}
```

### PR DESCRIPTION
**Pull request by sanketsingh24**
Closes #3265 

- This PR fixes the bug in which the aspect ratio was not being maintained when resizing. The error was the child `_renderer` in `_curCamera` was getting out of sync after `pop()` call in `setattributes()`.   
- @Spongman  suggested the solution for this bug. Also added the sketch I was using in manual tests. 
- Need suggestions for whether the sketch should be merged, and if yes, where it should be present.

### CODE REVIEW

File: src/webgl/p5.RendererGL.js [hunk 1]
```diff
@@ -365,6 +365,12 @@ p5.prototype.setAttributes = function(key, value) {
   this.push();
   this._renderer._resetContext(attr);
   this.pop();
+  if (
+    this._renderer._curCamera._renderer !== this._renderer &&
+    this._renderer._curCamera.cameraType === 'default'
```
Comment (Spongman) [inline src/webgl/p5.RendererGL.js]: i'm not sure the `cameraType` check is necessary here.

i think this check can be as simple as
```javascript
if (this._renderer._curCamera) {
  this._renderer._curCamera._renderer = this._renderer;
}
```

Comment (sanketsingh24) [reply src/webgl/p5.RendererGL.js]: The idea behind `cameraType` check was taking precautions rather than waiting for a bug to appear but at this moment, I was not able to think of a situation where this could go wrong.

For the second suggestion, I think that could work for sure, didn't think of that while implementing. I think the current code is better in terms of readability, but anyways I will add a comment .

Comment (Spongman) [reply src/webgl/p5.RendererGL.js]: i can understand the precaution, but it seems to me that the bug here is that the camera's `_renderer` property is wrong (once the renderer has been switched out), and that this is the case regardless of the `cameraType`. At this point in the code, the old renderer has been discarded - it's no longer attached to the canvas.

Honestly i'd rather that the camera didn't hold onto the renderer at all: the back reference is a design smell and this kind of state-related bug is why.

File: test/manual-test-examples/webgl/setattribute/sketch.js [hunk 2]
```diff
@@ -0,0 +1,12 @@
+function setup() {
+  createCanvas(640, 480, WEBGL);
+  setAttributes('foobar', true);
```
Comment (stalgiag) [inline test/manual-test-examples/webgl/setattribute/sketch.js]: Might as well make this a real attribute

File: test/manual-test-examples/webgl/setattribute/index.html [hunk 3]
```diff
@@ -0,0 +1,20 @@
+<!DOCTYPE html>
```
Comment (stalgiag) [inline test/manual-test-examples/webgl/setattribute/index.html]: perhaps this can go in the `/manual-test-examples/webgl/camera/setAttributes`?

File: src/webgl/p5.RendererGL.js [hunk 4]
```diff
@@ -365,6 +365,9 @@ p5.prototype.setAttributes = function(key, value) {
   this.push();
   this._renderer._resetContext(attr);
   this.pop();
+  if (this._renderer._curCamera) {
+    this._renderer._curCamera._renderer = this._renderer;
+  }
```
Comment (stalgiag) [inline src/webgl/p5.RendererGL.js]: Great! I would say that it might be a good idea to put a test into `test/unit/webgl/p5.Camera.js`. Something to the effect of:
```
test('Camera is Renderer is correctly set after setAttributes', function() {
      var myCam2 = myp5.createCamera();
      assert.deepEqual(myCam2, myp5._renderer._curCamera);
      myp5.setAttributes('antialias', true);
      assert.deepEqual(myCam2._renderer, myp5._renderer);
    });
```
will probably be good. Though some more general state consistency tests may be in order soon.

Comment (sanketsingh24) [reply src/webgl/p5.RendererGL.js]: Will the suite `RendererGL Current Camera` a good place for this test?

Comment (stalgiag) [reply src/webgl/p5.RendererGL.js]: Yes that sounds good!

**Comment by stalgiag** [comment]
Thank you for the contribution!
