### PR TITLE
fixing problems with video element scaling

### LINKED ISSUE #1848: Video on canvas has incorrect width.
```javascript
var vid;

function setup() {
  createCanvas(320, 240);
  background(51);
  vid = createCapture(VIDEO);
  vid.size(320, 240);
  vid.hide();
}

function draw() {
  image(vid, 0, 0, width, height);
}
```

This is producing a video on canvas with the width of video source divided in half. 
I have the latest version of p5js: 0.5.7
Anyone else see this issue?

### PR DESCRIPTION
**Pull request by mlarghydracept**
Closes #1848 

The implementation is kind of unseemly but this handles every combination of scaling with image(), size(), and changes to pixel density. Hopefully we can make image() more readable in the future but for now this works as expected in all the cases I could test.

Also tested on example code in #1745, #1673, and #1079

### CODE REVIEW

File: src/image/loading_displaying.js [hunk 1]
```diff
@@ -223,7 +221,14 @@ p5.prototype.image =
   var pd = 1;
 
   if (img.elt && img.elt.videoWidth && img.elt.style.width && !img.canvas) {
-    pd = img.elt.videoWidth / parseInt(img.elt.style.width, 10);
+    //if img.elt.size() has been used and no width passed to image()
+    if(img.elt.style.width && !dWidth){
+      pd = img.elt.videoWidth / parseInt(img.elt.style.width, 10);
```
Comment (lmccart) [inline src/image/loading_displaying.js]: to clean this a little, we can pull out the `parseInt(img.elt.style.width, 10);` part and do that division at the end. that is, reformat lines 223-235 to first check img.elt, then do the other checks inside that if structure, then doing the final division at the end.

```javascript
if (img.elt) {
  if (img.elt.videoWidth && ...
  } ...
  pd /= parseInt(img.elt.style.width, 10);
}

**Comment by lmccart** [comment]
i commend your ability to forge past the cringeworthiness of this general code area and make a patch!
