### PR TITLE
#6164 Fixes inability to display single-frame GIFs

### LINKED ISSUE #6164: Problem with loadImage() from version 0.10.0 onwards
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

0.10.0 and later

### Web browser and version

Chrome Version 113.0.5672.134 (Official Build) (64-bit)

### Operating System

Google Chrome OS Version 113.0.5672.134 (Official Build) (64-bit)

### Steps:
I was checking some of my old sketches from a few years back which load images from Wikimedia Commons. They were working fine: the sketch rendered the images to the canvas. But when I updated p5 to the latest version no images were rendered. I narrowed it down to the problem occurring between releases 0.9.0 and 0.10.0. Any release 0.9.0 and earlier works fine and the images are rendered; any release from 0.10.0 onwards and the images are not rendered.
Here's a [basic sketch that demonstrates the problem](https://editor.p5js.org/piecesofuk/sketches/stgrFjOcY). If p5.js version 0.9.0 is used then a dog is rendered to the canvas, if the version is changed to 0.10.0 (in index.html) or later nothing appears, the p5 code...

### Snippet:

```js

let img;

function preload() {
  img = loadImage("https://upload.wikimedia.org/wikipedia/commons/1/13/Icon_bicolour_dog.gif");
}
function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(img);
}
```

### PR DESCRIPTION
**Pull request by ozramos**
Resolves #6164

 ## Changes:
- Removes if statement that caused single frame GIFs to be ignored
- Adds a single frame test GIF (converted `\docs\yuidoc-p5-theme\assets\rockies.jpg` -> `rockies.gif`)
- Adds a manual test that loads a single frame and animated GIF side by side (animated GIF from same folder)

## Screenshots of the change:

Manual test is here: `./test/manual-test-examples/p5.Image/load-gifs.html`
- Gif on left is a single-frame GIF
- GIF on right was from `\docs\yuidoc-p5-theme\assets\arnott-wallace-eye-loop-forever.gif`
- Also tested with external image to confirm (see dog), but didn't include in case of copyright

ezgif com-video-to-gif (3)
image

#### PR Checklist
- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md

### CODE REVIEW

File: src/image/loading_displaying.js [hunk 1]
```diff
@@ -598,106 +598,104 @@ function _createGif(
...
+    loopLimit = 1;
+  } else if (loopLimit === 0) {
+    loopLimit = null;
   }
 
+  // we used the pImg for painting and saving during load
+  // so we have to reset it to the first frame
+  pImg.drawingContext.putImageData(frames[0].image, 0, 0);
+
+  pImg.gifProperties = {
```
Comment (davepagurek) [inline src/image/loading_displaying.js:688]: How do you feel about adding the if statement back just on this block here? If there's just one frame in the gif, if we don't set gifProperties, we can maybe save a few cpu cycles by avoiding trying to calculate what frame it should be on by treating it like a normal image from here on out.  At least I think so anyway, your new tests will help confirm it 🙂

**Review by davepagurek — COMMENTED** [review]
Thanks for taking this on! I think this looks good, I just had one idea I left in a comment for some extra optimization. But if it turns out that that doesn't work, your current implementation is good too!

File: src/image/loading_displaying.js (hunk 1 above)
Comment (davepagurek) [reply src/image/loading_displaying.js:688]: I think that should fix the test that's currently taking, which has the title "single frame gif should not have gifProperties". But if there are other complications, it's not the end of the world if they do have that, so we can talk about updating the test if we can't get it to work otherwise.

Comment (ozramos) [reply src/image/loading_displaying.js]: Wow this is great feedback thanks! It's exactly why I was hoping to contribute :)

I totally agree and have submitted the conditional! But I'm kinda new to PRs so I'm not sure if they were added to this one...it looks like they were?

I took some time to look at where else gifProperties is being used but I think this is safe because the first frame is stored into the pImg, which is what eventually gets drawn. One thing to note is that this may prevent the ability add extra frames later (for example, to make use of the automatic GIF features), but that might not be intended anyways

Comment (davepagurek) [reply src/image/loading_displaying.js]: Right, I think we don't have any officially documented APIs for adding frames to imported gifs so I think we should be good!

**Review by davepagurek — APPROVED** [review]
Great work @ozramos!

**Comment by davepagurek** [comment]
@all-contributors please add @ozramos for code
