### PR TITLE
[fix] Splitting methods in dom module

### LINKED ISSUE #4410: Splitting up methods as individual functions in favour of readability and testing
In dom module, [methods CreateDiv, CreateP, CreateSpan](https://github.com/processing/p5.js/blob/f176e7029df9c5f0b34709a378a5e897039927ec/src/dom/dom.js#L376-L400) are bundled up which makes it hard to discover them. It is not good for testing and breaks pattern of how methods should be written. So in favor of ease of readablility and testing, i would like to write them individually.

### PR DESCRIPTION
**Pull request by fenilgandhi**
Resolves #4410 

 Changes:
Split up methods for  createDiv, createP, createSpan

 Screenshots of the change:

#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/master/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/master/contributor_docs#unit-tests

### CODE REVIEW

File: src/dom/dom.js [hunk 1]
```diff
@@ -348,6 +348,11 @@ function addElement(elt, pInst, media) {
  * createDiv('this is some text');
  * </code></div>
  */
+p5.prototype.createDiv = function(html) {
+  let elt = document.createElement('div');
+  if (typeof html !== undefined) elt.innerHTML = html;
```
Comment (akshay-99) [inline src/dom/dom.js]: Use a string here. 
`typeof html !== 'undefined'`
`typeof something` gives the type of something but as a string.
This will remove the test failure

File: src/dom/dom.js [hunk 2]
```diff
@@ -361,6 +366,11 @@ function addElement(elt, pInst, media) {
  * createP('this is some text');
  * </code></div>
  */
+p5.prototype.createP = function(html) {
+  let elt = document.createElement('p');
+  if (typeof html !== undefined) elt.innerHTML = html;
```
Comment (akshay-99) [inline src/dom/dom.js]: here too

File: src/dom/dom.js [hunk 3]
```diff
@@ -373,15 +383,11 @@ function addElement(elt, pInst, media) {
...
-  var method = 'create' + tag.charAt(0).toUpperCase() + tag.slice(1);
-  p5.prototype[method] = function(html) {
-    var elt = document.createElement(tag);
-    elt.innerHTML = typeof html === 'undefined' ? '' : html;
-    return addElement(elt, this);
-  };
-});
+p5.prototype.createSpan = function(html) {
+  let elt = document.createElement('span');
+  if (typeof html !== undefined) elt.innerHTML = html;
```
Comment (akshay-99) [inline src/dom/dom.js]: and here

File: src/dom/dom.js (hunk 1 above)
Comment (fenilgandhi) [reply src/dom/dom.js]: yes, that would solve this. but still the tests fail. I m looking into it.

Comment (fenilgandhi) [reply src/dom/dom.js]: found the issue, this tests are not updated. there is another commit which enhances the tests. Need to find a middle out
