### PR TITLE
fix: prevent browser freeze when tessellating >50k vertices (dev-2.0)

### LINKED ISSUE #8219: Browser freeze when creating >65k vertices in draw() loop (no validation or warning)
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] p5.strands
- [x] WebGL
- [ ] DevOps, Build process, Unit testing
- [ ] Internationalization (i18n)
- [x] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.11.10 (also tested on 2.0.5,issue exists in all versions)

### Web browser and version

all browser

### Operating system

windows 11

### Steps:
1. Paste the code below into the p5.js web editor (editor.p5js.org)
2. Click "Play"
3. Wait 1-2 seconds

### Snippet:

```js
function setup() {
  createCanvas(400, 400, WEBGL);
}

function draw() {
  background(200);
  beginShape();
  
  // Creating 100,000 vertices (exceeds 65k limit)
  for (let i = 0; i < 100000; i++) {
    vertex(random(-200, 200), random(-200, 200), random(-200, 200));
  }
  
  endShape();
}

```

### PR DESCRIPTION
**Pull request by Nixxx19**
### Resolves #8219 for the dev-2.0 branch

This is the dev-2.0 port of #8555.

### Summary
- Adds a one-time confirmation prompt before tessellating very large PATH-mode shapes (>50,000 vertices) to avoid browser freezes in `libtess`.
- **Cancel**: skips tessellation and draws nothing for that shape.
- **OK**: remembers the choice for the lifetime of the renderer via `_largeTessellationAcknowledged` and tessellates normally without prompting again.
- Respects `p5.disableFriendlyErrors`: when disabled, tessellation always runs with no prompt.

### Tests
Added unit tests in `test/unit/webgl/p5.RendererGL.js` under the `beginShape() in WEBGL mode` suite, written in vitest syntax (`vi.spyOn` / `mockImplementation`). All 4 tests pass locally.

### CODE REVIEW

**Comment by Nixxx19** [comment]
Screenshot 2026-04-17 at 3 57 22 PM

File: src/webgl/ShapeBuilder.js [hunk 1]
```diff
@@ -148,6 +148,29 @@ export class ShapeBuilder {
     }
 
     if (this.shapeMode === constants.PATH) {
+      const vertexCount = this.geometry.vertices.length;
+      const MAX_SAFE_TESSELLATION_VERTICES = 50000;
+
+      if (vertexCount > MAX_SAFE_TESSELLATION_VERTICES) {
+        const p5Class = this.renderer._pInst.constructor;
```
Comment (davepagurek) [inline src/webgl/ShapeBuilder.js:155]: Ah yes this is one of the currently kinda awkward bits of 2.x now that we've split core functionality into addons: there is not always a global p5. The way we're currently dealing with this is with a sort of "dependency injection" pattern of sorts, where we make a function on the current class, like in this case maybe `friendlyErrorsDisabled() { return false; }`, and then in an addon file inside of `function myAddon(p5, fn, lifecycles) { ... }`, we override that function with a real implementation. Take a look in this PR at how we've given p5.Image access to `p5.friendlyError`: https://github.com/processing/p5.js/pull/8676/changes#diff-fdf1c89a0511ed981f59e9539de1ff707da1e75c7b21f35184406cacb5781672

Let's maybe try to follow a similar pattern here where we override `ShapeBuilder.friendlyErrorsDisabled` (or whatever we choose to call it) from within the addon function that adds the WebGL renderer to p5?

Comment (Nixxx19) [reply src/webgl/ShapeBuilder.js]: thanks for the pointer! yeah that pattern makes way more sense, the `_pInst.constructor` thing was definitely awkward. added a `friendlyErrorsDisabled()` on `ShapeBuilder` that returns false by default, and then overrode it inside the `renderer3D` addon where `p5` is in scope to actually check `p5.disableFriendlyErrors`. tests still pass. let me know if you had something slightly different in mind!

**Review by davepagurek — APPROVED** [review]
Looks good, thanks!
