### PR TITLE
Tried an approch for text case in pixelmatch

### LINKED ISSUE #7496: [p5.js 2.0 Beta Bug Report]: Update image diff algorithm in snapshot tests to be less tolerant
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [x] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

2.0 beta 1

### Web browser and version

N/A

### Operating system

N/A

### Steps to reproduce this

I was just working on https://github.com/processing/p5.js/pull/7495, and found that the change I made to `src/shape/custom_shapes.js` line 398 did not cause existing visual tests to change:
```diff
- points.unshift(this.vertices.at(-1), prevVertex);
+ points.unshift(this.vertices.at(-1));
```

Snapshot tests should have low enough tolerance that this change would cause a test to fail. However, simply reducing the `shiftThreshold` or even switching to the mapbox `pixelmatch` package caused many false negative failures on CI. This is because rendering on different platforms is different enough that it's sometimes more than just what `pixelmatch` detects as an antialiasing difference (for example, sometimes rendered text is shifted a pixel down.) We want these to be acceptable differences.

I'm not sure what options we have here, but if anyone has other libraries they want to test, or updates to our custom diff code, I'd love to hear your ideas!

### PR DESCRIPTION
**Pull request by Vaivaswat2244**
Resolves #7496

 Changes:

Modified the `checkMatch` function in `visualtest.js` to be more tolerant of slight text position shifts while still catching meaningful changes. Key changes:

Added text detection using pixel pattern analysis:

- Looks for moderate density and high contrast transitions typical of text
- Helps identify regions where small shifts should be allowed

Implemented shift tolerance for text regions:

- Allows up to 2-pixel shifts for detected text areas
- Still fails on actual content changes
- Configurable via `shiftThreshold` parameter

 Screenshots of the change:

#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline reference] is included / updated
- [x] [Unit tests] are included / updated

[Inline reference]: https://p5js.org/contribute/contributing_to_the_p5js_reference/
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by davepagurek** [comment]
Thanks @Vaivaswat2244, nice approach! I have a few questions that might help us determine how to get this across the finish line.

- Do you have a sense of how often `isLikelyText` returns true, and if this gets called on anything non-text? I wonder if maybe rather than trying to detect whether we think there is text, we can directly record when `text` is called. Since we pass in a p5 instance to the test case anyway, maybe we can do something like this to patch `text()` to record that it got called:

  ```js
  let hasText = false
  const prevText = myp5.text
  myp5.text = function(...args) {
    hasText = true
    prevText.apply(this, args)
  }
  ```
  
 - It looks like [some tests are failing on CI now.](https://github.com/processing/p5.js/actions/runs/13353056666/job/37292021733?pr=7552) Do you know if these look like (1) false positives that the checker needs to address, (2) cases where we need to regenerate the screenshots because the old ones were out of date but still passed on CI under the old pixel checker, or (3) are actual bugs in p5 that are surfaced now by using a better pixel checker?

**Comment by Vaivaswat2244** [comment]
yeah sure, the text() passing makes much more sense. I can implement that.
And regarding the tests getting failed. I think that these are the 2nd case as you described, failed the CI tests after regenerating on my machine but were passed by the old checker. Also I'm not so sure how to move ahead from here. So ig for now I'll change the text case and will see how that works out.

**Comment by davepagurek** [comment]
Are you able to see the test output from CI on your PR by clicking the Details button here?
image

For a next step, I'd look at the test output, and try regenerating the failed screenshots locally and pushing those. We can see if that fixes it on CI, and also by looking at the new images in the Files Changed tab, whether we think the changed images are expected.

**Comment by Vaivaswat2244** [comment]
hey, so I just noticed that the files which I added in the earlier commit aren't the one which are failing the tests on CI, but they are other files which were not touched.

Now, I changed the files which were failing tests in CI, and tried the tests locally. The tests are now failing for different files in the typography and webgl cases. I guess there is a problem with my changes in the visualtest file.
So maybe I'll revert these changes and think of something else.

**Comment by davepagurek** [comment]
Just looking at the last failure in the test file:

Expected:
image

Received:
image

Diff:
image

...it looks like a few isolated pixels are off. I wonder if we can do something to augment pixelmatch and check if the difference exists just on a single pixel (so no surrounding pixels are also flagged) and then ignore those?

**Comment by Vaivaswat2244** [comment]
Sure, I can try that

**Comment by davepagurek** [comment]
Nice, the clustering idea is good and gives us some options for dealing with issues like this! I suspect if a shape is consistently 1px thick, then it could be the result of a shift due to environment differences. 

A way to check that might be to try to see if, for every pixel in the cluster, it has at most two neighbours?

**Comment by Vaivaswat2244** [comment]
I have made some changes to this, so now additional to clustering logic our algo does the following
- Iterates through all 8 neighboring pixels (excluding itself) to determine how many are part of the difference.
- If more than 80% of the pixels in the cluster have ≤2 neighbors, the difference is classified as a line shift (isLineShift = true).

Using this and keeping the thresholds same as the more tolerable [commit](https://github.com/processing/p5.js/pull/7552/commits/8f50108ca23b05e38ee3647f9c3d05d05fa9738d), the tests are now passing.
After a game of trial and error in  the thresholds, found that 0.5 for pixelmatch is optimum for us, as this is passing the tests in default cases. And in the pr #7495 , I reversed the changes and added pervVertex and the test which you added failed. 

Expected:
image

Recieved:
image

Diff: 
image

So is there anything else I should change.

File: test/unit/visual/visualTest.js [hunk 1]
```diff
@@ -88,55 +89,213 @@ export function visualSuite(
...
+        const clusterSize = findClusterSize(diffCanvas.pixels, x, y, width, height, 1, visited);
+        clusterSizes.push(clusterSize);
+      }
+    }
+  }
+  
+  // Define significance thresholds
+  const MIN_CLUSTER_SIZE = 4;  // Minimum pixels in a significant cluster
+  const MAX_TOTAL_DIFF_PIXELS = 40;  // Maximum total different pixels
+  const MAX_LINE_SHIFT_PIXELS = 200;
```
Comment (davepagurek) [inline test/unit/visual/visualTest.js:177]: Does this get used?

**Review by davepagurek — COMMENTED** [review]
Awesome, this is looking really promising, great work! I think the algorithm is in a spot where it's good to go. The last thing might be to add a comment somewhere explaining the general approach of the diff algorithm, similar to what you've described in comments to me here, and maybe additionally why it's necessary at all (because contributors running tests just on their own system might not realize that there will be differences on CI.)

File: test/unit/visual/visualTest.js [hunk 2]
```diff
@@ -88,55 +89,213 @@ export function visualSuite(
...
-
-  // Long screenshots end up super tiny when fit to a small square, so we
-  // can double the max side length for these
   const ratio = expected.width / expected.height;
   const narrow = ratio !== 1;
   if (narrow) {
     scale *= 2;
   }
-
+
```
[the remark this answers is not in the document]
Comment (Vaivaswat2244) [reply test/unit/visual/visualTest.js:97]: Right!

File: test/unit/visual/visualTest.js (hunk 1 above)
Comment (Vaivaswat2244) [reply test/unit/visual/visualTest.js:177]: Yeah these are getting used in the check match function itself for final comparison. 
Variation of these thresholds also causes variations in the tests results as well, like the Min_Cluster_Size if reduced from this makes our test less tolerable and can cause false CI fails like we saw in the isolated pixel case.

**Review by davepagurek — APPROVED** [review]
