### PR TITLE
Fix: allow single-arg atan() outside strands; add unit test

### LINKED ISSUE #8092: [p5.js 2.0 Bug Report]: atan() logs an error when used outside strands
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [x] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

2.0.5

### Web browser and version

All

### Operating system

All

### Steps:
1. Use `atan()` outside of a shader
2. It logs `p5.js says: It looks like you've called atan outside of a shader's modify() function.` and returns undefined rather than working properly

This looks like the same issue as https://github.com/processing/p5.js/issues/8026 and likely needs to be fixed the same way as https://github.com/processing/p5.js/pull/8036

### Snippet:

```js
function setup() {
  createCanvas(400, 400);
  console.log(atan(0.5))
}
```
Live: https://editor.p5js.org/davepagurek/sketches/cJ6IjhxqP

### PR DESCRIPTION
**Pull request by Abhayaj247**
**Resolves #8092**

- The single-argument `atan(x)` was incorrectly treated as GLSL-only in strands, causing a friendly error and returning undefined when called outside a shader. This mirrors the `noise()` override issue fixed in #8036.
- The fix marks the 1-arg overload as a normal p5 function while keeping the 2-arg GLSL overload `atan(y, x)` strands-only.

**Changes :**

- src/webgl/ShaderGenerator.js
  - In `builtInGLSLFunctions`, set:
     - `atan` single-arg overload: `isp5Function: true`
     - `atan` two-arg overload: remains `isp5Function: false`

- test/unit/visual/cases/math.js
   - Add `atan_outside_strands` visual integration test that draws the value of `atan(0.5)` to ensure it evaluates and no friendly error is triggered.

- test/unit/spec.js
   - Include the new visual test suite entry `visual/cases/math`.

**Screenshots of the change :**

- Visual test creates baseline showing text like “atan(0.5) ≈ 0.464”; subsequent runs match the baseline.

**PR Checklist :**
- [x] npm run lint passes
- [x] [Inline reference] is included / updated (function behavior unchanged; no reference edits needed)
- [x] [Unit tests] are included / updated (added visual/integration test)

[Inline reference]: https://p5js.org/contribute/contributing_to_the_p5js_reference/
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Review by davepagurek — COMMENTED** [review]
Thanks for making this! Since the atan test is just checking the value of the result, I think it makes more sense to do a regular unit test rather than a visual test (it's a lot computationally cheaper to compare numbers with `expect(val).toEqual(...)` than to compare all the pixels in an image, do you think we could put the test in one of our unit test files instead?

**Comment by Abhayaj247** [comment]
Thanks for the feedback @davepagurek , I’ve moved the atan tests to a dedicated unit test file at `test/unit/math/atan.js` . The tests now verify correct numerical results for single-argument usage and ensure the two-argument (GLSL-only) case returns `undefined` outside of strands. This keeps the tests efficient, focused, and aligned with the intended testing strategy - helping maintain clarity in the suite.

Please let me know if you need any further adjustments.

File: test/unit/math/atan.js [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+    };
+
+    // Initialize trigonometry functions on mock
+    trigonometry(mockP5, mockP5Prototype);
+
+    // Save original atan (from trigonometry)
+    const originalAtan = mockP5Prototype.atan;
+
+    // Override atan to handle one-arg and two-arg correctly
+    mockP5Prototype.atan = function(...args) {
```
Comment (davepagurek) [inline test/unit/math/atan.js]: Can we test the actual `atan` without testing a mock version? I think the only thing we really need a test for is just that, outside of strands, you can call `atan` with one argument, which it already supports without needing an override.

Comment (davepagurek) [reply test/unit/math/atan.js]: The reason being, it becomes a bit unclear how much of the functionality we're testing is just in the mock once we start doing this.

Comment (Abhayaj247) [reply test/unit/math/atan.js]: Hi @davepagurek ,

I’ve updated the atan unit test to only verify single-argument behavior (in both radians and degrees) using the actual function, without overriding or mocking it.

```

import trigonometry from '../../../src/math/trigonometry.js';
import { assert } from 'chai';

suite('atan', function() {
  const mockP5 = {
    RADIANS: 'radians',
    DEGREES: 'degrees',
    _validateParameters: () => {}
  };
  const mockP5Prototype = {};

  beforeEach(function() {
    mockP5Prototype._angleMode = mockP5.RADIANS;
    mockP5Prototype.angleMode = function(mode) {
      this._angleMode = mode;
    };
    trigonometry(mockP5, mockP5Prototype);
  });

  test('should return the correct value for atan(0.5) in radians', function() {
    mockP5Prototype.angleMode(mockP5.RADIANS);
    const expected = Math.atan(0.5);
    const actual = mockP5Prototype.atan(0.5);
    assert.closeTo(actual, expected, 1e-10);
  });

  test('should return the correct value for atan(0.5) in degrees', function() {
    mockP5Prototype.angleMode(mockP5.DEGREES);
    const expected = Math.atan(0.5) * 180 / Math.PI;
    const actual = mockP5Prototype.atan(0.5);
    assert.closeTo(actual, expected, 1e-10);
  });
});

```

Could you please confirm if this approach looks good before I commit and push the changes?

Thanks!

Comment (davepagurek) [reply test/unit/math/atan.js]: That approach looks right! maybe just evaluate the two functions on a calculator to get as specific of a value to compare to as possible for your radians and degrees cases.

Comment (Abhayaj247) [reply test/unit/math/atan.js]: Thanks for the clarification @davepagurek. I’ve updated the tests to directly compare against pre-calculated values for atan(0.5) in both radians and degrees. Here’s the full updated test file :

```

import trigonometry from '../../../src/math/trigonometry.js';
import { assert } from 'chai';

suite('atan', function() {
  const mockP5 = {
    RADIANS: 'radians',
    DEGREES: 'degrees',
    _validateParameters: () => {}
  };
  const mockP5Prototype = {};

  beforeEach(function() {
    mockP5Prototype._angleMode = mockP5.RADIANS;
    mockP5Prototype.angleMode = function(mode) {
      this._angleMode = mode;
    };
    trigonometry(mockP5, mockP5Prototype);
  });

  test('should return the correct value for atan(0.5) in radians', function() {
    mockP5Prototype.angleMode(mockP5.RADIANS);
    const expected = 0.4636476090008061; // pre-calculated value
    const actual = mockP5Prototype.atan(0.5);
    assert.closeTo(actual, expected, 1e-10);
  });

  test('should return the correct value for atan(0.5) in degrees', function() {
    mockP5Prototype.angleMode(mockP5.DEGREES);
    const expected = 26.56505117707799; // pre-calculated value
    const actual = mockP5Prototype.atan(0.5);
    assert.closeTo(actual, expected, 1e-10);
  });
});

```

Could you confirm if this looks good before I push the changes? Happy to make any further adjustments if needed.

Comment (davepagurek) [reply test/unit/math/atan.js]: looks good!

Comment (Abhayaj247) [reply test/unit/math/atan.js]: Thank you for reviewing and confirming, @davepagurek! I’ve pushed the changes accordingly. Please let me know if there’s anything else needed.

**Review by davepagurek — APPROVED** [review]
thanks for the PR!

**Comment by Abhayaj247** [comment]
Thank you for your guidance throughout this process. I look forward to contributing more.
