### PR TITLE
skip FES checks on internal calls

### LINKED ISSUE #7817: [p5.js 2.0 Bug Report]: Internal calls to p5 functions are checked by FES
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [x] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

2.0.2

### Web browser and version

Firefox

### Operating system

MacOS

### Steps to reproduce this

In this sketch https://editor.p5js.org/davepagurek/sketches/Ty-01oHgN, in the console, you'll see the FES message: "p5.js says: Expected at most 1 argument, but received more in createVector()."

This specific error is due to https://github.com/processing/p5.js/issues/7741 and has since been fixed in 2.0.2, but you'll notice the error is about `createVector`, but the sketch's code does not actually directly call `createVector`. It is coming from *inside of `worldToScreen`* here: https://github.com/processing/p5.js/blob/2a86107bbd7a40370ed713092994f7f748124a30/src/core/environment.js#L1388

This scenario could be improved for two reasons:
- If we internally use a non-documented parameter pattern, users will be seeing a warning for code they didn't write and can't change. This seems pretty confusing for them.
- If we internally use a valid parameter pattern, we are spending extra time checking parameters that should already be correct since it's an internal usage. (If it's incorrect, FES is probably not the right spot to surface the issue anyway.)

My recommendation here is to **not run FES parameter checking on internal function calls.**

### Implementation notes

For synchronous function calls, we can keep track of how deeply nested a function call is by modifying the FES wrapper here: https://github.com/processing/p5.js/blob/2a86107bbd7a40370ed713092994f7f748124a30/src/core/friendly_errors/param_validator.js#L561-L564
...to be something more like this, which keeps track of a nesting level, and only checks params at the first level:
```js
this[f] = function(...args) {
  this.level = (this.level || 0) + 1;
  if (this.level === 1) {
    this.validate(f, args);
  }
  const result = copy.call(this, ...args);
  this.level--;
  return result;
};
```
This doesn't quite solve the issue for asynchronous functions, since multiple can be running at once, with the runtime jumping back and forth between their execution contexts. Maybe only doing this for synchronous contexts is good enough for now? I'm open to ideas for other implementations that also handle the async case!

### PR DESCRIPTION
**Pull request by avinxshKD**
Resolves #7817

## Changes

Added call depth tracking to skip FES param validation on internal p5 function calls. The decorator now sets `_isUserCall` flag and only validates at the outermost level. For async contexts (load* methods), added `_internal()` helper to suppress validation after await points.

Modified 5 shader loading functions in `src/webgl/material.js` to wrap post-await internal calls: `loadFilterShader`, `loadMaterialShader`, `loadNormalShader`, `loadColorShader`, `loadStrokeShader`.

Fixes the issue where users see FES warnings for internal p5 calls they didn't write (like `createVector` inside `worldToScreen` and avoids redundant param checking on already-validated internal calls.

## Screenshots of the change

N/A - internal behavior change, no visual differences

#### PR Checklist

- [ ] `npm run lint` passes
- [ ] [Inline reference] is included / updated
- [ ] [Unit tests] are included / updated

[Inline reference]: https://p5js.org/contribute/contributing_to_the_p5js_reference/
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by avinxshKD** [comment]
@davepagurek hey let me know if any adjustments needed, happy to work thanks

File: src/core/friendly_errors/param_validator.js [hunk 1]
```diff
@@ -573,14 +573,32 @@ function validateParams(p5, fn, lifecycles) {
...
+  };
+
   p5.decorateHelper(
     /^(?!_).+$/,
     function(target, { name }){
       return function(...args){
-        if (!p5.disableFriendlyErrors && !p5.disableParameterValidator) {
-          validate(name, args);
+        const wasInternalCall = this._isUserCall;
+        this._isUserCall = true;
```
Comment (ksen0) [inline src/core/friendly_errors/param_validator.js]: ~Seems like this line would result in all calls being internal? What am I missing?~ I understood it but maybe it would be nice to add a comment for this block and the block above, noting that if one logic is updated the other should probably be reviewed, as they are similar but not quite same.

**Comment by avinxshKD** [comment]
@ksen0 Hey, hve added cross-reference comments linking the two blocks, both now have NOTE lines pointing to each other.

File: src/webgl/material.js [hunk 2]
```diff
@@ -1814,9 +1814,9 @@ function material(p5, fn) {
   fn.loadNormalShader = async function (url, onSuccess, onFail) {
     try {
       const cb = await urlToStrandsCallback(url);
-      let shader = this.withGlobalStrands(this, () =>
+      let shader = this._internal(() => this.withGlobalStrands(this, () =>
```
Comment (davepagurek) [inline src/webgl/material.js:1857]: Nice! While we're at it, can we do the other known methods? In the reference it looks like that means `loadModel`, `loadFont`, `loadImage`, `loadBlob`, `loadBytes`, `loadJSON`, `loadStrings`, `loadTable`, and `loadXML`

**Comment by avinxshKD** [comment]
hey @davepagurek you mean  [_internal()](vscode-file://vscode-app/c:/Users/avina/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) applied to ALL load* methods, not just the shader ones.Right??

checked all of them:

- `loadJSON`, `loadStrings`, `loadTable`, `loadXML`, `loadBytes`, `loadBlob`  no `this.` calls at all post-await, they just return data or pass to `successCallback`
- `loadImage` : works on the `p5.Image` instance and browser APIs, no `this.method()` calls
- `loadFont` : uses `fn.parseFontData` directly (bypasses the decorator entirely) and a module-level `create()` helper
- `loadModel` :  operates on the `Geometry` instance (`model.normalize()` etc), no `this.method()` calls

None of them hit a decorated `p5.prototype` method after an await, so wrapping wouldn't change behavior. The 5 shader loaders in material.js are the only ones that actually call `this.buildXxxShader()` / `this.createFilterShader()` post-await

Should I add wrapping to the others anyway for consistency/future-proofing, or is the current scope (just the shader loaders) what you had in mind? Want to make sure I'm not missing somethin

**Comment by davepagurek** [comment]
Awesome, thanks for looking into all of those!

> Should I add wrapping to the others anyway for consistency/future-proofing, or is the current scope (just the shader loaders) what you had in mind? Want to make sure I'm not missing somethin

I think it's not a bad idea to add the wrapping anyway so that we don't have to remember in the future.

**Comment by avinxshKD** [comment]
Hey thanks for reviewing @ksen0  @davepagurek Added [_internal()](vscode-file://vscode-app/c:/Users/avina/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) wrapping to all remaining load* methods, [loadJSON](vscode-file://vscode-app/c:/Users/avina/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html), [loadStrings](vscode-file://vscode-app/c:/Users/avina/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html), [loadTable](vscode-file://vscode-app/c:/Users/avina/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html), [loadXML](vscode-file://vscode-app/c:/Users/avina/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html), [loadBytes](vscode-file://vscode-app/c:/Users/avina/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html), [loadBlob](vscode-file://vscode-app/c:/Users/avina/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html), [loadImage](vscode-file://vscode-app/c:/Users/avina/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html), [loadFont](vscode-file://vscode-app/c:/Users/avina/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html), [loadModel](vscode-file://vscode-app/c:/Users/avina/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html).

None of them currently call [this.method()](vscode-file://vscode-app/c:/Users/avina/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) post-await, so this is purely future-proofing. Uses a safe guard ([this._internal ? this._internal(cb) : cb()](vscode-file://vscode-app/c:/Users/avina/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html)) since [_internal](vscode-file://vscode-app/c:/Users/avina/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) isn't available in test mocks where param_validator doesn't run

**Comment by avinxshKD** [comment]
Hey @davepagurek @ksen0 have resolved the merge conflict in [param_validator.js](vscode-file://vscode-app/c:/Users/avina/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) by keeping the branch’s internal-call guard logic and adapting it to upstream’s new [registerDecorator](vscode-file://vscode-app/c:/Users/avina/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/workbench.html) API. No extra refactor, no behavior changes outside conflict resolution. Thanks lmk if you have any suggestions
