### PR TITLE
Webgl Point Added

### LINKED ISSUE #2662: beginShape(POINTS) not working in WebGL
It will display line instead of points in under WebGL renderer. Tested in both Safari and Chrome.

### PR DESCRIPTION
**Pull request by AdilRabbani**
Added point for WebGL. This is based on the fragment shader provided by @aferriss #3017 . Uses default square points for small points and circular points for larger ones. Closes #2662 #2184

### CODE REVIEW

File: src/webgl/p5.RendererGL.Immediate.js [hunk 1]
```diff
@@ -326,4 +335,29 @@ p5.RendererGL.prototype._drawStrokeImmediateMode = function() {
   this._pInst._pixelsDirty = true;
 };
 
+p5.RendererGL.prototype.initPointVertexBufferImmediate = function() {
```
Comment (mlarghydracept) [inline src/webgl/p5.RendererGL.Immediate.js]: This function name feels a little bit long and misleading. It is doing more than simple initialization. One could argue that the line 51 with the call to `createBuffer()` is the actual immediate mode point vertex buffer initialization. This function is doing something a little closer to drawing. Could you change the name to something a little bit shorter and with an underscore to indicate its privacy like `_drawPoints(points, amt)`? Notice I also put arguments in that example. I think it would be fairly simple to collapse the immediate and retained mode versions of this into a single function at the renderer level.

File: src/webgl/primitives.js [hunk 2]
```diff
@@ -744,7 +744,14 @@ p5.prototype.torus = function(radius, tubeRadius, detailX, detailY) {
 
 //@TODO
 p5.RendererGL.prototype.point = function(x, y, z) {
```
Comment (mlarghydracept) [inline src/webgl/primitives.js]: Make sure to write the comment text for generating an example in the docs.

File: src/webgl/shaders/point.vert [hunk 3]
```diff
@@ -0,0 +1,11 @@
+attribute vec3 vPosition;
+uniform float vPointSize;
```
Comment (mlarghydracept) [inline src/webgl/shaders/point.vert]: I would try to keep the naming convention from the other shaders. These should use that first letter to indicate the type of data. So this would be `uPointSize`. [The light vertex shader](https://github.com/processing/p5.js/blob/master/src/webgl/shaders/light.vert) has good naming conventions.

File: test/manual-test-examples/webgl/point/sketch.js [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+    randStroke_g = Math.floor(Math.random() * 255 + 1);
+    randStroke_b = Math.floor(Math.random() * 255 + 1);
+    randStrokeWeight = Math.floor(Math.random() * 10 + 1);
+    stroke(randStroke_r, randStroke_g, randStroke_b);
+    strokeWeight(randStrokeWeight);
+    randX = Math.floor(Math.random() * (-800 - 800 + 1)) + 800;
+    randY = Math.floor(Math.random() * (-600 - 600 + 1)) + 600;
+    point(randX, randY);
+  }
+}
```
Comment (mlarghydracept) [inline test/manual-test-examples/webgl/point/sketch.js]: This is good. I would also add an example for immediate mode drawing that pushes the number of points being drawn to a much higher number.

Comment (kjhollen) [reply test/manual-test-examples/webgl/point/sketch.js]: Great suggestion. I'm also wondering—does this flash the dots quickly? If so, I suggest using noLoop() in setup or setting the frameRate to only update the drawing every ~5 seconds. The flashing/strobing effect may be harmful to some viewers.

File: src/webgl/shaders/point.vert (hunk 3 above)
Comment (kjhollen) [reply src/webgl/shaders/point.vert]: Some documentation of the existing shader uniforms [can be found here in webgl_mode_architecture.md](https://github.com/processing/p5.js/blob/ef774d56336eeb9781d340fc069ac2e1e85e26f0/developer_docs/webgl_mode_architecture.md)—and it would be great to add a column for the point shader at the end of this document!

File: src/webgl/p5.RendererGL.Retained.js [hunk 5]
```diff
@@ -336,4 +336,31 @@ p5.RendererGL.prototype._drawElements = function(drawMode, gId) {
...
 
+p5.RendererGL.prototype.initPointVertexBuffer = function(x, y, z) {
+  var gl = this.GL;
+
+  var pointVertexBuffer = gl.createBuffer();
+
+  this._bindBuffer(
+    pointVertexBuffer,
+    gl.ARRAY_BUFFER,
+    [x, y, z],
```
Comment (kjhollen) [inline src/webgl/p5.RendererGL.Retained.js]: Hmm, seeing this, I wonder if some slight performance gains can be made by making an array once and keeping it around.

File: src/webgl/shaders/point.frag [hunk 6]
```diff
@@ -1,7 +1,7 @@
 precision mediump float;
 precision mediump int;
-uniform vec4 color;
-varying float v_strokeWeight;
+uniform vec4 uColor;
```
Comment (kjhollen) [inline src/webgl/shaders/point.frag]: Could this be uMaterialColor to better match other shaders? Or is it a distinctly different property?
