### PR TITLE
Fix: Added unique group names for radio buttions

### LINKED ISSUE #6763: Radio buttons interact with each other
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [X] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.9.0

### Web browser and version

Brave	1.61.116 Chromium: 120.0.6099.217

### Operating system

Windows 11

### Steps:
1. Create two radio buttons (with multiple option)
2. Set a selected value for each
3. Only the last selected value will be selected
4. Selecting a value on the first radio will unselect all options from the second radio

### Snippet:

```js
function setup() {
  createCanvas(100, 100);

  const radio1 = createRadio();
  radio1.option('car');
  radio1.option('bicycle');
  radio1.option('airplane');
  radio1.selected('bicycle');
  
  const radio2 = createRadio();
  radio2.option('tiger');
  radio2.option('elephant');
  radio2.option('parrot');
  radio2.selected('tiger');
}
```

### PR DESCRIPTION
**Pull request by Forchapeatl**
This PR ensures unique names for each radio button group in createRadio function
Resolves #6763 

Resolves #6763 

 Changes:

- Added a Counter for Unique Radio button Names
- Modified the `self._name` Assignment

 Screenshots of the change:

https://github.com/user-attachments/assets/9da27258-29b3-4f2d-9515-0288d4be1305

#### PR Checklist

- [x]  `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

File: src/dom/dom.js [hunk 1]
```diff
@@ -1738,6 +1723,10 @@ p5.prototype.createRadio = function(...args) {
   return self;
 };
 
+// Initialize counter for unique radio group names
+p5.prototype.createRadio.counter = 0;
```
Comment (ashish1729) [inline src/dom/dom.js:1727]: I wonder if p5's prototype is a good place to keep this counter, although I am not much aware of the code base to provide an alternative.

Comment (Forchapeatl) [reply src/dom/dom.js:1727]: thank you for the review ,  please where is the prototype class . I will be happy to keep the counter there. I am still learning the structure of the codebase.

Comment (ashish1729) [reply src/dom/dom.js:1727]: I see that we are not adding anything new to the `prototype` of p5 ... we are adding to `createRadio` which is already  there, so I guess this can be OK, you can ignore my previous comment

**Comment by limzykenneth** [comment]
I see many of the existing code comments are removed, is there a reason for that?

File: src/dom/dom.js (hunk 1 above)
Comment (limzykenneth) [reply src/dom/dom.js:1727]: I'm not sure attaching to `createRadio` as a property is a good idea here. If it is just something that is kept tracked of internally, it can just be a scoped variable, ie. `let counter = 0`.

Comment (Forchapeatl) [reply src/dom/dom.js:1743]: When I use  `let counter = 0`  within the function’s scope, the counter  resets with each call to `createRadio`, and causes duplicate names like `radioOption_0` for multiple radio groups.  When I attach the counter to `p5.prototype.createRadio`, each group gets a unique identifier (e.g., `radioOption_1`, `radioOption_2`), avoiding potential conflicts between radio groups.

Comment (limzykenneth) [reply src/dom/dom.js:1743]: The `let` statement should be outside of the function scope, it can be in the file scope as the bundler won't leak file level local variable to the larger environment.

**Comment by Forchapeatl** [comment]
>I see many of the existing code comments are removed, is there a reason for that?
I have placed  back the comments

**Comment by limzykenneth** [comment]
Looks good. Thanks!
