### PR TITLE
Fix: Preserve canvas position when calling noSmooth() in WEBGL

### LINKED ISSUE #7548: noSmooth() breaks positioned WEBGL canvas
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.11.3

### Web browser and version

Chrome 133.0.6943.54

### Operating system

MacOS

### Steps:
1. `createCanvas()`, position it, add `noSmooth()` in the `draw()`
2. 2D renderer, no problem
3. WEBGL, breaks, creates new empty canvas?

Perhaps one isn't supposed to use `noSmooth()` in the draw? I don't remember hitting this issue, but maybe never tried it before... Is that how it's supposed to behave? The [refs](https://p5js.org/reference/p5/noSmooth/) only show examples of it in the `setup()`, but it doesn't state anywhere that's the only spot for it to go. In 2D renderer, it doesn't cause an issue, so is it normal in WEBGL or a bug?

### Snippet:

```js

function setup() {
	let cvn = createCanvas(300, 300)
	cvn = createCanvas(300, 300, WEBGL) // breaks with noSmooth() below
	cvn.position(150, 50)
	
	background(0, 0, 255)
	circle(0, 0, 100)
}

function draw(){
	noSmooth() // breaks sketch in WEBGL mode
}

```

### PR DESCRIPTION
**Pull request by ImRAJAS-SAMSE**
## **Changes:**
- **Prevents unnecessary canvas recreation** in `p5.RendererGL.js` by ensuring `noSmooth()` does not trigger a full reset in WebGL mode.  
- **Preserves canvas positioning** when calling `noSmooth()`, avoiding unintended resets when `position(x, y)` is used.  

## **Screenshots of the Change:**  
  
✅ *The canvas now maintains its position correctly after calling `noSmooth()`.*  

---

### **✅ PR Checklist**
- [x] `npm run lint` passes  
- [x] [Inline reference] is included / updated  
- [x] [Unit tests] are included / updated  

[Inline reference]: https://p5js.org/contribute/contributing_to_the_p5js_reference/  
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by ImRAJAS-SAMSE** [comment]
Hi @davepagurek,  

I've rebased my changes onto `dev-2.0` and ran `npm test`. Most of the tests have passed, but I encountered **7 WebGL test failures**, including a **visual test mismatch**.  

Since my fix involves preventing unnecessary canvas recreation in WebGL mode, some tests might need updating. Should I update the reference screenshots or investigate further?  

The **other tests and linting checks are successful**. Let me know how you'd like to proceed!  

Thanks!

File: src/webgl/p5.RendererGL.js [hunk 1]
```diff
@@ -930,15 +930,22 @@ class RendererGL extends Renderer {
     const w = this.width;
     const h = this.height;
     const defaultId = this.canvas.id;
-    const isPGraphics = this._pInst instanceof Graphics;
+    const isPGraphics = this._pInst instanceof p5.Graphics;
```
[the remark this answers is not in the document]
Comment (ImRAJAS-SAMSE) [reply src/webgl/p5.RendererGL.js:933]: Got it! I'll turned off my auto-formatter and will remove the `p5.` prefix, including the one in `Element.call(...).` Let me know if there's anything else I should adjust. Thanks for the review.

**Comment by ImRAJAS-SAMSE** [comment]
Hi @davepagurek,

All tests have now passed, and I’ve turned off my auto-formatter to prevent unnecessary diffs in future too. Let me know if anything else needs adjustment. Thanks!

File: src/webgl/p5.RendererGL.js [hunk 2]
```diff
@@ -932,13 +932,20 @@ class RendererGL extends Renderer {
...
+    };
+
     if (isPGraphics) {
       const pg = this._pInst;
       pg.canvas.parentNode.removeChild(pg.canvas);
       pg.canvas = document.createElement("canvas");
       const node = pg._pInst._userNode || document.body;
       node.appendChild(pg.canvas);
-      Element.call(pg, pg.canvas, pg._pInst);
+      p5.Element.call(pg, pg.canvas, pg._pInst);
```
Comment (davepagurek) [inline src/webgl/p5.RendererGL.js:948]: Does this still work if we take off the p5 prefix here too as it was before?

```suggestion
      Element.call(pg, pg.canvas, pg._pInst);
```

**Review by davepagurek — COMMENTED** [review]
Thanks, I'm glad to see tests are working now! The last thing I think we'll want to do is to add a unit test to make sure that future changes to p5 won't accidentally break this change without us knowing. We could add a test that changes the position of a webgl canvas, then calls noSmooth, and then checks to see that the new element has the same position style attributes as before?

Let me know if I can help explain anything about unit testing in p5!

File: src/webgl/p5.RendererGL.js (hunk 2 above)
Comment (ImRAJAS-SAMSE) [reply src/webgl/p5.RendererGL.js:948]: Yes, I tested it after removing the p5. prefix, and everything works correctly. The canvas still preserves its position after calling noSmooth().

**Comment by ImRAJAS-SAMSE** [comment]
Added a unit test to verify that noSmooth() preserves canvas position in WebGL. Also added comments in p5.RendererGL.js for clarity. All tests passed locally, but one CI test is still failing.

File: test/unit/webgl/test_noSmoothCanvasPosition.js [hunk 3]
```diff
@@ -0,0 +1,26 @@
+import { describe, it, expect } from 'vitest';
+
+// Importing p5 
+import '../../../lib/p5.js';
```
Comment (davepagurek) [inline test/unit/webgl/test_noSmoothCanvasPosition.js:4]: I think this import is giving it trouble because `lib` is only built on release or when manually built.

Other test files tend to import p5 differently (see for example `test/unit/webgl/RendererGL.js`.) It might be easier (and maybe more organized too) to actually just put this test case into the existing `RendererGL` test file, as then you can just use the `myp5` variable it has already imported and created.

Comment (ImRAJAS-SAMSE) [reply test/unit/webgl/test_noSmoothCanvasPosition.js:4]: Got it! I'll move the test into p5.RendererGL.js and reuse the existing myp5 instance. Thanks for the suggestion!

**Comment by ImRAJAS-SAMSE** [comment]
Moved the noSmooth() canvas position test to` p5.RendererGL.js` as suggested and removed the old test file. All tests and lint checks have passed. Are there any more adjustments needed. Thanks

**Review by davepagurek — APPROVED** [review]
Thanks @ImRAJAS-SAMSE, everything looks good to go!

**Comment by davepagurek** [comment]
@all-contributors please add @ImRAJAS-SAMSE for code
