### PR TITLE
Fix set() to support p5.Graphics objects

### LINKED ISSUE #2984: Should P5.Graphics support set() with another P5.Graphics?
#### Nature of issue?

- [X] Found a bug

#### Most appropriate sub-area of p5.js?

- [X] Color
- `createGraphics()`
- `set()`

#### Which platform were you using when you encountered this?

- [X] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 0.6.1 (using the alpha web editor)
- Web browser and version: Chrome 67.0.3396.62
- Operating System: Linux
- Steps to reproduce this:

From [this](https://stackoverflow.com/q/50764508/873165) Stack Overflow question.

It appears that the `set()` function does not work with `P5.Graphics` values. Is this expected?

```
let redRect;

function setup() {
  createCanvas(100,100);
  redRect = createGraphics(100,100);
  redRect.fill(255, 0, 0);
  redRect.rect(20,20,40,40);
	
  const blueRect = createGraphics(20, 20);
  blueRect.background(0, 0, 255);
  redRect.set(30, 30, blueRect);
  redRect.updatePixels();
}

function draw() {
  background(0, 255, 0);
  image(redRect,0,0);
}
```

I would expect this to create a graphics that contains a red rectangle, and then draw a blue rectangle to that first graphics. Instead, only a single pixel is set, and it's set to transparent?

red rectangle on green background

### PR DESCRIPTION
**Pull request by VANSH3104**
Resolves #2984

 Changes:

 Screenshots of the change:

### Before vs After Comparison

| Before | After |
|--------|-------|
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |
| image | image |

#### PR Checklist

- [ x] `npm run lint` passes
- [ ] [Inline reference] is included / updated
- [ ] [Unit tests] are included / updated

[Inline reference]: https://p5js.org/contribute/contributing_to_the_p5js_reference/
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by VANSH3104** [comment]
@ksen0 @davepagurek I've implemented the fix for set() to support p5.Graphics objects. The solution adds a check for Graphics instances in p5.Renderer2D.prototype.set() and uses drawImage() with the graphics canvas directly (avoiding .get() as suggested).

**Comment by VANSH3104** [comment]
@ksen0, is this change satisfactory or is there anything further that needs to be done?

**Comment by VANSH3104** [comment]
Hi @ksen0 and @davepagurek,
Just following up on this PR. All checks are passing, and the implementation aligns with the approach discussed earlier by handling p5.Graphics directly via drawImage and avoiding .get() for performance and WebGPU compatibility.
Whenever you have time to review, please let me know if any changes, refinements, or additional tests are needed. I’m happy to continue working on this.
Thanks for your time.

**Comment by VANSH3104** [comment]
@ksen0 or @davepagurek , could you please review this so that I can continue working on it?.

File: src/core/p5.Renderer2D.js [hunk 1]
```diff
@@ -541,7 +541,16 @@ class Renderer2D extends Renderer {
     // round down to get integer numbers
     x = Math.floor(x);
     y = Math.floor(y);
-    if (imgOrCol instanceof Image) {
+    if (imgOrCol instanceof Graphics) {
+      this.drawingContext.save();
```
Comment (davepagurek) [inline src/core/p5.Renderer2D.js:555]: This looks good, is the code in this branch the same as in the Image branch though? if so maybe we can simplify this by using an `||` condition and just having it be one branch?

**Comment by VANSH3104** [comment]
@davepagurek I have added your recommendation and also test cases. Should I also add manual test examples?

File: src/core/p5.Renderer2D.js (hunk 1 above)
Comment (VANSH3104) [reply src/core/p5.Renderer2D.js:555]: Yes, they are the same. I will update it.

**Review by davepagurek — COMMENTED** [review]
Thanks, this is looking almost ready to go! I think tests for just this feature don't need to be in their own file, can we move them into maybe https://github.com/processing/p5.js/blob/dev-2.0/test/unit/core/rendering.js ?

**Comment by VANSH3104** [comment]
@davepagurek I have added the test to your preferred location. Please let me know if anything else is required. ?

**Comment by VANSH3104** [comment]
Is this perfect or do I need to make changes?

**Comment by davepagurek** [comment]
@all-contributors please add @VANSH3104 for code
