### PR TITLE
fixes issue #7366: Adjust Option Orientation in CreateRadio() reference.

### LINKED ISSUE #7366: Adjust Option Orientation in CreateRadio() reference.
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [X] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

_No response_

### Web browser and version

_No response_

### Operating system

_No response_

### Steps:

1. Go to link : https://p5js.org/reference/p5/createRadio/
2. See the reference

In PR https://github.com/processing/p5.js/pull/7315 we noticed,

image

A proper alignment would be nice to have.

### PR DESCRIPTION
**Pull request by Prajyot05**
Resolves #7366 

 Changes:
Added styling to the radio, hence aligning them one below the other.

 Screenshots of the change:
Screenshot 2024-11-08 at 5 10 49 PM

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by Prajyot05** [comment]
is this change appropriate?

**Comment by perminder-17** [comment]
Thanks @Prajyot05 for your work on this. @devesh-2002, Do you want to review this code, since you were interested in solving this issue and it was assigned to you previously.

**Comment by Prajyot05** [comment]
@perminder-17 are any changes required or should I raise a PR?

**Comment by perminder-17** [comment]
> @perminder-17 any updates?

I'll review it today. Thanks for your work and your patience. Been really busy this week. So sorry for the delay.

**Comment by Prajyot05** [comment]
@perminder-17 No problem sir, I hope I can help solve the issue

File: src/dom/dom.js [hunk 1]
```diff
@@ -1463,15 +1463,28 @@ p5.prototype.createSelect = function(...args) {
...
+ * document.head.appendChild(style);
+ *
  * let myRadio;
  *
  * function setup() {
  *   createCanvas(100, 100);
  *
  *   // Create a radio button element and place it
- *   // in the top-left corner.
+ *   // in the top-right corner.
```
Comment (perminder-17) [inline src/dom/dom.js:1484]: Okay, so we are rendering in a 2D canvas and it's coordinates at 0,0 represents a top-left corner. If it was a webgl canvas (0,0) represented the mid of the canvas. So it should be top-left

File: src/dom/dom.js [hunk 2]
```diff
@@ -1535,9 +1548,10 @@ p5.prototype.createSelect = function(...args) {
...
```
Comment (perminder-17) [inline src/dom/dom.js:1551]: here as well, it should be top-left corner.

**Comment by Prajyot05** [comment]
oh ok, I'll fix that, is the rest fine?

**Review by perminder-17 — APPROVED** [review]
Thanks for your patience and your work. Looks good to me.

**Comment by Prajyot05** [comment]
@perminder-17  any updates on this?

**Comment by davepagurek** [comment]
I think this is good for now! Ideally there would be a way to do this without having to create a custom style tag like this, but it does seem like maybe the best option currently. Maybe worth making a new issue to make the default behaviour nicer?
