### PR TITLE
fixed second example in the reference page for `acos()` 

### LINKED ISSUE #6696: Incorrect example in the reference page for acos()
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [X] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.9.0

### Web browser and version

Google Chrome 120.0.6099.200 (Official Build) (64-bit) 

### Operating System

Windows 10 Pro Version 22H2

### Steps:
1. Visit the reference page for `acos()` - https://p5js.org/reference/#/p5/acos
2. It has 2 examples - both with the same output, although it is clear from the `describe` function of the second example that it is supposed to have a different output:

acos

I want to work on this issue!

### PR DESCRIPTION
**Pull request by sudhanshuv1**
Resolves #6696 

 Changes:

Changed the value of `a` from `PI` to `PI-QUARTER_PI` in the second example in reference for `acos()` (in file `src/math/trigonometry.js` ). Also changed `3.927` to `2.356` in `describe` in this example.

 Screenshots of the change:

change

#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

File: src/math/trigonometry.js [hunk 1]
```diff
@@ -42,14 +42,14 @@ p5.prototype._angleMode = constants.RADIANS;
  *
  * <div>
  * <code>
- * let a = PI;
+ * let a = PI-QUARTER_PI;
```
Comment (nickmcintyre) [inline src/math/trigonometry.js:45]: Please add space around the operator for readability, as in `PI - QUARTER_PI`

**Review by nickmcintyre — CHANGES_REQUESTED** [review]
Good catch @sudhanshuv1! Please make a tiny tweak and we'll merge this.

File: src/math/trigonometry.js (hunk 1 above)
Comment (sudhanshuv1) [reply src/math/trigonometry.js]: Thanks, I made the desired changes, and also changed `a` to `PI + QUARTER_PI` so the output would exactly match the statement we have currently in the `describe` function.

Comment (nickmcintyre) [reply src/math/trigonometry.js]: Looks good!

**Review by nickmcintyre — APPROVED** [review]
Thanks @sudhanshuv1!
