### PR TITLE
Rest types

### LINKED ISSUE #7741: [p5.js 2.0 Beta Bug Report]: createVector(x, y, z) shows FES message
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [x] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

Latest dev-2.0

### Web browser and version

Firefox

### Operating system

MacOS

### Steps:
Calling `createVector(x, y, z)` currently shows this message:

```
p5.js says: Expected at most 1 argument, but received more in createVector(). For more information, see https://p5js.org/reference/p5/createVector. 
```

Looks like maybe the doc comments are out of date on `createVector`?

### Snippet:

```js
function setup() {
  createCanvas(200, 200)
  createVector(1, 2, 3)
}
```

### PR DESCRIPTION
**Pull request by davepagurek**
Resolves #7741

Changes:
- Checks for rest params (e.g. `createVector(...params: Number[])`) when parsing jsdoc
- Updates parameter data and typescript types for rest params
- Handle checks for rest params in FES

#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline reference] is included / updated
- [x] [Unit tests] are included / updated

[Inline reference]: https://p5js.org/contribute/contributing_to_the_p5js_reference/
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

File: test/unit/core/param_errors.js [hunk 1]
```diff
@@ -253,6 +253,29 @@ suite('Validate Params', function () {
       ];
       const result = mockP5Prototype.validate('p5.paletteLerp', [colorStops, 0.5]);
       assert.isTrue(result.success);
-    })
-  })
+    });
+  });
+
+  suite('validateParams: rest arguments', function () {
```
Comment (ksen0) [inline test/unit/core/param_errors.js:259]: Thank you!
