### PR TITLE
Erode, dilate, threshold shader filters match closer to CPU filters

### LINKED ISSUE #6398: Discrepancies with shader-based THRESHOLD, ERODE, and DILATE Filters at higher pixel densities
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [X] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.7.x Beta: https://raw.githubusercontent.com/wong-justin/p5.js/shader-filters-build/lib/p5.js

### Web browser and version

Chrome Version 116.0.5845.140 (Official Build) (arm64)

### Operating System

MacOS Ventura 13.4 (22F66)

### Steps to reproduce this

_Note: this is a follow up to the conversation on https://github.com/processing/p5.js/pull/6324_

Big thanks to @wong-justin, @aferriss, and @aceslowman for getting the shader-based filters up and running in p5.js

I've spotted some quirks in the outputs of `filter(THRESHOLD)`, `filter(ERODE)`, and `filter(DILATE)` when we increase the pixel density. At `pixelDensity(1)`, things look similar to the CPU-based filter, but once we increase the density, some discrepancies start to appear in the output.

For more clarity, I've put together a demo sketch [here](https://editor.p5js.org/SableRaf/sketches/Rvd-Hznpt). You can also see the differences in this generated images:

### `pixelDensity(1)`
image

### `pixelDensity(2)`
image

### PR DESCRIPTION
**Pull request by wong-justin**
Resolves #6398 

Changes (discussed in the issue above but summarized again here):
- THRESHOLD shader tweaked to match CPU filter more closely. Still a few pixels different, but close enough
- ERODE, DILATE shaders use luminance values to exactly match CPU filters
- `texelSize` accounts for pixel density now

 Screenshots of the change:

| Before | After|
|--------|--------|
|  |  |

#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

### CODE REVIEW

File: src/webgl/p5.RendererGL.js [hunk 1]
```diff
@@ -1096,7 +1099,7 @@ p5.RendererGL = class RendererGL extends p5.Renderer {
     else {
       pg.shader(this.filterShader);
       this.filterShader.setUniform('tex0', this);
-      this.filterShader.setUniform('texelSize', [1/this.width, 1/this.height]);
+      this.filterShader.setUniform('texelSize', texelSize);
       this.filterShader.setUniform('canvasSize', [this.width, this.height]);
```
Comment (aferriss) [inline src/webgl/p5.RendererGL.js:1103]: Should these values also be multiplied by pixel density?

**Comment by aferriss** [comment]
Thanks for making the PR Justin! Apologies for steering you wrong initially with the non-luminance based erode/dilate filters but I'm glad we got there in the end.

It looks good to me!

File: src/webgl/p5.RendererGL.js (hunk 1 above)
Comment (davepagurek) [reply src/webgl/p5.RendererGL.js:1103]: This is a good question. I think ideally, we'd want to make the shader handle pixel density rather than the user calling the filter function so that it's easier to make density-agnostic sketches. That means the shader would likely want to know about both the width and the pixel density. I think right now this is possible by comparing `texelSize` and `canvasSize`, but wouldn't be possible if we also multiply by pixel density here. (Maybe it's worth adding `pixelDensity` as a separate uniform so it doesn't always have to be calculated by dividing the other two?)

**Review by davepagurek — APPROVED** [review]
Nice work @wong-justin!

File: src/webgl/p5.RendererGL.js (hunk 1 above)
Comment (wong-justin) [reply src/webgl/p5.RendererGL.js:1103]: I was thinking maybe all shader uniforms should account for pixel density, ie. `texelSize = 1 / (width * pixelDensity), 1 / (height * pixelDensity)` and `canvasSize = width * pixelDensity, height * pixelDensity`. That way they would all be doing work at the same level of resolution. Although having `canvasSize != width, height` is probably not what the user expects.

**Comment by wong-justin** [comment]
Ah yep @aferriss, antialiasing makes a ton of sense. Sure enough, rects match up perfectly.

**Comment by Qianqianye** [comment]
Thanks @wong-justin for working on it and @davepagurek for the approval. @aferriss, do you think this PR is ready to be merged? Thanks!

**Comment by aferriss** [comment]
Yes, lgtm!!
