### PR TITLE
Fix 'this.elt.srcObject is null' error

### LINKED ISSUE #4908: "this.elt.srcObject is null" error when removing a MediaElement (video)
- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [X] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

#### Details about the bug:

- p5.js version: 1.1.9
- Web browser and version: Firefox 83.0 (64-bit)
- Operating System: Linux / Ubuntu

- Also reproduced on Chrome 86.0.4240.198 / Windows 10 Pro

- Steps to reproduce this:
Add a video element and later try to remove it.
The remove() method throws an error and doesn't proceed.
Error message : "this.elt.srcObject is null"

- Code snippet:

```
let vid;

function setup() {
  noCanvas();

  vid = createVideo(
    ['video.webm', 'video.mov'],
    vidLoad
  );  

  vid.size(100, 100);
}

function vidLoad() {
    vid.loop();
    setTimeout(function() {
        vid.remove();
    }, 1000)
}
```

I solved the issue with this code but I'm not sure it won't have side-effects on other types of MediaElement 
```

          * Removes the element, stops all media streams, and deregisters all listeners.
           * @method remove
           * @example
           * <div class='norender'><code>
           * let myDiv = createDiv('this is some text');
           * myDiv.remove();
           * </code></div>
           */
          _main.default.Element.prototype.remove = function() {
            // stop all audios/videos and detach all devices like microphone/camera etc
            // used as input/output for audios/videos.
            if (this instanceof _main.default.MediaElement) {
                this.stop(); // Stop the MediaElement
                var sources = this.elt.srcObject;
                if (undefined != sources) { // Only proceed if sources is not null
                    var tracks = sources.getTracks();
                    tracks.forEach(function(track) {
                        track.stop();
                    });
                }
            }
```

### PR DESCRIPTION
**Pull request by KKVANONYMOUS**
Resolves #4908 

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

File: src/dom/dom.js [hunk 1]
```diff
@@ -2173,10 +2173,14 @@ p5.Element.prototype.remove = function() {
   // stop all audios/videos and detach all devices like microphone/camera etc
   // used as input/output for audios/videos.
   if (this instanceof p5.MediaElement) {
-    const tracks = this.elt.srcObject.getTracks();
-    tracks.forEach(function(track) {
-      track.stop();
-    });
+    this.stop();
+    let sources = this.elt.srcObject;
```
Comment (lmccart) [inline src/dom/dom.js:2177]: I think `let` could be `const` on this line and the line two below here. otherwise looks good!

Comment (KKVANONYMOUS) [reply src/dom/dom.js]: @lmccart I have resolved the issue. Please have a look

**Comment by lmccart** [comment]
thanks!
