### PR TITLE
textToContours is broken under textAlign(CENTER,CENTER) and use linebreak

### LINKED ISSUE #8079: [p5.js 2.0 Bug Report]: textToContours is broken under textAlign(CENTER,CENTER) and use linebreak
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [x] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

2.0.5

### Web browser and version

Chrome

### Operating system

Windows

### Steps:
1. Use textToContours with 4 arguments, and use linebreak for texts.
2. It works fine when alignment is LEFT and TOP.
3. However, if alignment is CENTER,CENTER, it will not work properly.

### Snippet:

[DEMO](https://openprocessing.org/sketch/2718397)
```js
let font;

async function setup() {
  createCanvas(400, 400);
  font = await loadFont('https://inaridarkfox4231.github.io/assets/fonts/SourceSerif4.ttf');
  
  background(200);
  textAlign(LEFT,TOP); // no error
  //textAlign(CENTER, CENTER); // error
  textSize(120);
  
  // Get the point array.
  let contours = font.textToContours("H\nY", width/2, height/2, { sampleFactor: 0.5 });
  
  beginShape();
  for (const pts of contours) {
    beginContour();
    for (const pt of pts) {
      vertex(pt.x, pt.y);
    }
    endContour(CLOSE);
  }
  endShape();
}
```

## case: LEFT,TOP

Image

## case: CENTER,CENTER

Image

### Additional Information
It seems to work fine with 6 arguments.

Image

It's clear that no errors occur. However, I don't understand the specifications, so I don't know anything more. It's a wierd function. I can’t help.

Probably here is the cause for this:
[_parseArgs](https://github.com/processing/p5.js/blob/dev-2.0/src/type/p5.Font.js#L753)

However, this is just a guess, and even if this was the cause, I don't know how to fix it.

That's all.

### PR DESCRIPTION
**Pull request by perminder-17**
Resolves #8079

### CODE REVIEW

File: src/type/textCore.js [hunk 1]
```diff
@@ -1905,12 +1905,15 @@ function textCore(p5, fn) {
...
     if (lines.length > 1) {
-      // Call the 2D mode version: the WebGL mode version does additional
-      // alignment adjustments to account for how WebGL renders text.
-      boxes.forEach(bb =>
-        bb.x += p5.Renderer2D.prototype._xAlignOffset
-          .call(this, textAlign, width)
-      );
+      // When width is not provided (e.g., fontBounds path), fall back to the widest line.
+      const maxWidth = boxes.length
+      ? boxes.reduce((m, b) => Math.max(m, b.w || 0), 0)
```
Comment (davepagurek) [inline src/type/textCore.js]: Super minor, but I think since you provide the initial value of 0 in the reduce, we don't additionally need to have a ternary on `boxes.length`; the `reduce` will already return 0 here.

File: test/unit/type/p5.Font.js [hunk 2]
```diff
@@ -40,6 +40,16 @@ suite('p5.Font', function () {
     assert.property(bbox, 'h');
   });
 
+   test('fontBounds no NaN (multiline + CENTER)', async () => {
+        const pFont = await myp5.loadFont(fontFile);
```
Comment (davepagurek) [inline test/unit/type/p5.Font.js]: Looks like the body of this test might be indented one time too many?

**Comment by perminder-17** [comment]
Thanks for your valuable feedback :)

**Review by davepagurek — APPROVED** [review]
Awesome, thanks for the fix!

**Comment by perminder-17** [comment]
> Awesome, thanks for the fix!

Always, a pleasure.
