### PR TITLE
Add unit tests for p5.prototype.select() and fix bugs

### LINKED ISSUE #1061: Unit test suite for p5.dom?
While working on #1047 and #1049 I noticed that there don't seem to be any unit tests for p5.dom--am I correct, or did I miss it somewhere?

If there is indeed no test suite for p5.dom, would you accept a PR for one?

### PR DESCRIPTION
**Pull request by toolness**
This fixes #1061 by adding a simple unit test suite for p5.dom which currently just tests the `p5.prototype.select()` function. I actually ran into two bugs in the function while testing it, so I fixed those.

Notes:
* There aren't currently any test suites for anything in the `lib/addons` directory, so I wasn't sure how to name the directory containing the p5.dom tests, since `test/unit` mirrors the structure of the `src` directory. Then I noticed #645 is about moving P5.dom into the core library, so I just put the test suite in a folder called `test/unit/dom`, thinking that perhaps P5.dom will eventually be moved into `src/dom` and then everything will make sense. In any case, I'm probably overthinking this...
* I didn't add anything to `test-minified.html` since it seems like there's no minified version of p5.dom available.

### CODE REVIEW

File: test/unit/dom/dom.js [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+
+        assert.strictEqual(select('.blarg').elt, elt);
+      });
+
+      test('should return null when elements by class are not found', function() {
+        assert.isNull(select('.blarg'));
+      });
+
+      test('should find elements by tag name', function() {
+        elt = document.createElement('aside');
```
Comment (toolness) [inline test/unit/dom/dom.js]: Basically I just wanted to use a tag name that was unlikely to exist elsewhere on `test.html`.

File: test/unit/dom/dom.js [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+        if (elt && elt.parentNode) {
+          elt.parentNode.removeChild(elt);
+          elt = null;
+        }
+      });
+
+      test('should find elements by ID', function() {
+        elt = document.createElement('div');
+        elt.setAttribute('id', 'blarg');
+        document.body.appendChild(elt);
```
Comment (toolness) [inline test/unit/dom/dom.js]: I considered just using p5.dom to do this work, but I decided against it, since it would make the tests less isolated (e.g. bugs in e.g. `remove()` would bleed into these tests). However, there are also arguments [against](http://c2.com/cgi/wiki?UnitTestIsolation) unit test isolation, so I'm curious what others think.

**Comment by lmccart** [comment]
thanks, these look great! we're holding off on integrating p5.dom for now to give it more time for the API to settle down, so I'm going to move these files into their own addons test folder.
