### PR TITLE
Reference-fixes

### LINKED ISSUE #8073: Reference fixes
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [x] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] p5.strands
- [ ] WebGL
- [ ] DevOps, Build process, Unit testing
- [ ] Internationalization (i18n)
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

>= 1.9(ish)

### Web browser and version

All

### Operating system

All

### Steps to reproduce this

I found a handful of typos, omissions, and errors in the reference while reviewing it this week 🤦🏽‍♂️ Here's a quick rundown:

- `stroke()` -- ...after calling `stroke()` will be **outlined** with the color orange...
- `fill()` -- The version of `fill()` with four parameters... **is missing**
- `background()` -- The version of `background()` with four parameters... **is missing**
- `endShape()` -- **Stops** adding vertices to a custom shape.
- `shearY()` -- In the example comments, `// Shear the coordinate system along the **y**-axis.`
- `applyMatrix()` -- Broken link: https://en.wikipedia.org/wiki/Transformation_matrix
- `arc()` -- The sentence "Arcs are always drawn clockwise from start to stop." is repeated; the second copy should be deleted.

### PR DESCRIPTION
**Pull request by Nitin2332**
Resolves #8073 

#### PR Checklist

- [ ] `npm run lint` passes
- [ ] [Inline reference] is included / updated
- [ ] [Unit tests] are included / updated

[Inline reference]: https://p5js.org/contribute/contributing_to_the_p5js_reference/
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

File: src/core/shape/vertex.js [hunk 1]
```diff
@@ -1342,7 +1342,7 @@ p5.prototype.endContour = function() {
 };
 
 /**
- * Begins adding vertices to a custom shape.
+ * Completes the custom shape defined with vertex() calls, and optionally closes it if CLOSE is passed.
```
Comment (perminder-17) [inline src/core/shape/vertex.js]: Here, you just need to write 

"Stops adding vertices to a custom shape."

File: src/color/setting.js [hunk 2]
```diff
@@ -996,6 +1014,10 @@ p5.prototype.colorMode = function(mode, max1, max2, max3, maxA) {
  * <a href="#/p5/colorMode">colorMode()</a>. The default color space is RGB,
  * with each value in the range from 0 to 255.
  *
+ * The version of `fill()` with four parameters interprets them as RGBA, HSBA,
```
Comment (perminder-17) [inline src/color/setting.js]:
```suggestion
 * The version of `fill()` with four parameters interprets them as `RGBA`, `HSBA`,
```

File: src/color/setting.js [hunk 3]
```diff
@@ -996,6 +1014,10 @@ p5.prototype.colorMode = function(mode, max1, max2, max3, maxA) {
...
+ * or HSLA colors, depending on the current <a href="#/p5/colorMode">colorMode()</a>. The last parameter
```
Comment (perminder-17) [inline src/color/setting.js]:
```suggestion
 * or `HSLA` colors, depending on the current <a href="#/p5/colorMode">colorMode()</a>. The last parameter
```

**Review by perminder-17 — APPROVED** [review]
Hi @Nitin2332 , thanks for your work on this. I'm going to merge this, but the issue still doesn't closes since we want these changes in `dev-2.0` branch as well. Are you interested in working on `dev-2.0` branch as well. If not, I can open up a PR targeting `dev-2.0` branch.

**Comment by nitin-rajpoot** [comment]
Hi @perminder-17 , thanks for merging this!
Yes, I’m interested in making the same changes in the dev-2.0 branch as well. I’ll create a new PR targeting dev-2.0.
