### PR TITLE
Fixed line drawing in WebGL when there is a previously defined texture

### LINKED ISSUE #5440: Can't draw a Line in WEBGL Renderer if previously a texture was defined
Hi,
when I want to draw a line with the WEBGL Renderer, it works no problem, but when I draw a 3D object with texture before that, the line won't be displayed.

- [x] WebGL
- p5.js version: 1.4.0
- Web browser and version: Google Chrome 94.0.4606.61
- Operating System: Windows
- Steps to reproduce this:
```
let g;
let gtex;
function preload(){
  g = loadModel('js/gimbal.obj',false);
  gtex = loadImage('js/gimbaltex.png');
}
function setup(){
  createCanvas(720, 240,WEBGL);
  ortho();
}
function draw(){
  smooth();
  clear();
  
  translate(0,0,-100);
  noStroke();
  directionalLight(255, 255, 255,0,0, 1);
  directionalLight(255, 255, 255,0,0, -1);
  rotateX(PI);
  push();
  translate(-240,0,0); 
  scale(4+(2/3));
  texture(gtex); // when I disable this texture (comment it out), the line gets drawn no problem, but otherwise not.
  model(g);
  stroke(255,0,0);
  noFill();
  line(0,0,0,100,100,100);
}
```
[files.zip](https://github.com/processing/p5.js/files/7290234/files.zip)
Here are the 3D Models!

Thanks
Bastian

### PR DESCRIPTION
**Pull request by leslieyip02**
Resolves #5440 

 Changes:
Removed `&& this.drawMode !== constants.TEXTURE` from `calculateStroke`.

 Screenshots of the change:

Using the example from #5440,

- Before:

Screenshot 2023-01-28 at 18-21-06 p5 js example

- After:

Screenshot 2023-01-28 at 18-02-46 p5 js example

#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by inaridarkfox4231** [comment]
Excuse me, what would the image function do in that case? Normally, I don't think diagonal lines are needed when displaying an image, so I think it would be better to declare "noStroke" internally, but I'm not sure if that's correct.

**Review by davepagurek — APPROVED** [review]
Thanks for making this change happen! I tested locally, looks good!

**Review by davepagurek — CHANGES_REQUESTED** [review]
Oh, the tests caught something I didn't test: drawing an image using `image()` now adds lines. Demo here, try toggling which p5 import in index.html is commented to see how p5 1.5.0 behaves: https://editor.p5js.org/davepagurek/sketches/nbzbYeVbp

I think we probably just need to call `noStroke()` in the WebGL implementation of `image()`: https://github.com/processing/p5.js/blob/main/src/webgl/3d_primitives.js#L1998

File: src/webgl/3d_primitives.js [hunk 1]
```diff
@@ -1995,6 +1995,7 @@ p5.RendererGL.prototype.image = function(
 
   this._pInst.noLights();
 
+  noStroke();
```
Comment (davepagurek) [inline src/webgl/3d_primitives.js:1998]: Right now the tests are still failing, I believe it's because we can't call the global `noStroke()` here in case p5 is running in instance mode. I think calling `this._pInst.noStroke()` should fix it though!

**Review by davepagurek — APPROVED** [review]
Awesome, thanks for making those changes!
