### PR TITLE
bugfix #6653 vertexNormal() is not defined,replaces with normal

### LINKED ISSUE #6653: `vertexNormal()` is not defined
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.9.0

### Steps to reproduce this
Run the example code from the `normal()` reference page, replacing calls to `normal()` with calls to `vertexNormal()`.

### Snippet:
```
function setup() {
  createCanvas(100, 100, WEBGL);
  noStroke();
}

function draw() {
  background(255);
  rotateY(frameCount / 100);
  normalMaterial();
  beginShape(TRIANGLE_STRIP);
  vertexNormal(-0.4, 0.4, 0.8);
  vertex(-30, 30, 0);

  vertexNormal(0, 0, 1);
  vertex(-30, -30, 30);
  vertex(30, 30, 30);

  vertexNormal(0.4, -0.4, 0.8);
  vertex(30, -30, 0);
  endShape();
}
```

### Suggested solution
Based on the reference, the two functions `vertexNormal()` and `normal()` serve the same purpose. Inspecting the source reveals that there's actually only one function; the reference page for the other function appears to have been generated by inline docs that use the wrong function name.

Specifically, there's a [reference page for `vertexNormal()`](https://p5js.org/es/reference/#/p5/vertexNormal), but that function is never defined in the p5.js codebase. The reference page is a stub that points to a file in the source that names `vertexNormal()` in the inline docs but implements the documented function with the name `normal()`. The naming mismatch between the inline docs and the implementation seems to have been present since this functionality was first introduced  in commit 072fac9949f176b702e6f7e8b625e28c7e730b66.  Fortunately, the mismatch is only present internally, in the version of the feature defined on p5.RendererGL.

Like the internal version, the user-facing version is implemented with `normal()` as the function name. [Its reference page](https://p5js.org/es/reference/#/p5/normal) is complete and uses the correct function name. So, this bug seems to have an easy fix: Replace `vertexNormal` in the documentation on lines [170](https://github.com/processing/p5.js/blob/cea9e09242d5d69bb83388b6fd03e8a09f1fdeed/src/webgl/p5.RendererGL.Immediate.js#L170) and [176](https://github.com/processing/p5.js/blob/cea9e09242d5d69bb83388b6fd03e8a09f1fdeed/src/webgl/p5.RendererGL.Immediate.js#L176) of `webgl/p5.RendererGL.Immediate.js` with `normal`. Since this is the only mention of `vertexNormal()` in the inline docs, I'm guessing this should effectively delete the associated page from the p5.js website's reference.

### PR DESCRIPTION
**Pull request by diyaayay**
Resolves #6653 

 Changes:

 ```
* Sets the normal to use for subsequent vertices.
 * @private
 * @method normal
 * @param  {Number} x
 * @param  {Number} y
 * @param  {Number} z
 * @chainable
 *
 * @method normal
 * @param  {Vector} v
 * @chainable
 */
```

 Screenshots of the change:

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Review by GregStanton — APPROVED** [review]

File: src/webgl/p5.RendererGL.Immediate.js [hunk 1]
```diff
@@ -167,13 +167,14 @@ p5.RendererGL.prototype.vertex = function(x, y) {
 
 /**
  * Sets the normal to use for subsequent vertices.
- * @method vertexNormal
+ * @private
```
Comment (davepagurek) [inline src/webgl/p5.RendererGL.Immediate.js:170]: I was initially wondering why this was `@private`, but for anyone else reading, it's because we already have public docs for `normal()` here: https://github.com/processing/p5.js/blob/v1.9.0/src/core/shape/vertex.js#L1107

This is just an internal method on the renderer that was accidentally producing a public doc before.

**Review by davepagurek — APPROVED** [review]
Thanks for fixing this!
