### PR TITLE
Replaced external call to googleapis with a call to the local server.

### LINKED ISSUE #629: Grunt fails mocha test due to timeout error
Grunt fails due to "lmccart: (slow internet connection culprit because it is loading an external json file from openweathermap.org)"

Failure error: 
 1) Files p5.prototype.loadJSON should allow json to override jsonp in 3rd param:
     timeout of 2000ms exceeded

### PR DESCRIPTION
**Pull request by workergnome**
This uses the internal server to serve up a JSON file for testing.  Fixes #629.

### CODE REVIEW

File: test/unit/input/files.js [hunk 1]
```diff
@@ -61,11 +61,12 @@ suite('Files', function() {
...
     test('should allow json to override jsonp in 3rd param',
       function(done){
-        var url = 'https://maps.googleapis.com/maps/api/geocode/json?address=Atlanta';
+
+        var url = 'http://localhost:9001/unit/input/array.json';
         var datatype = 'json';
         var myCallback = function(resp){
           assert.ok(resp);
-          //assert.typeOf(resp,'Object');
+          assert.typeOf(resp,'Array');
```
Comment (kadamwhite) [inline test/unit/input/files.js]: Since we have control over the source array, now, should we perhaps add an assertion that `resp.length === 3`? I'm ambivalent but raising it because it occurred to me as a possibility

**Comment by kadamwhite** [comment]
This is great, that'll reduce a major pain point in running these tests.

File: test/unit/input/files.js (hunk 1 above)
Comment (workergnome) [inline test/unit/input/files.js]: I have no objection to it, but I don't know that adding that adds any strength to the test?

**Comment by lmccart** [comment]
this is very helpful!
