### PR TITLE
Pass generated browserify bundle through derequire

### LINKED ISSUE #818: p5 with browserify gives "Error: Cannot find module '../core/core'" in v0.4.6 and v0.4.7
I seem to be running into errors when using p5js v0.4.6 and v0.4.7 with browserify. However, with v0.4.5, I have no issues. Browserify runs as expected. Any tips?

For example, if I run `browserify main.js -o bundle.js` on [this code](https://github.com/johnsojr/test-p5-browserify), I get these errors:

```
Error: Cannot find module '../core/core' from '/Users/jjohnson136/dev/p5-browserify-test/node_modules/p5/lib'
    at /Users/jjohnson136/.nvm/versions/node/v0.12.5/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/Users/jjohnson136/.nvm/versions/node/v0.12.5/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/jjohnson136/.nvm/versions/node/v0.12.5/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/jjohnson136/.nvm/versions/node/v0.12.5/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)
```

Thanks for any help!

### PR DESCRIPTION
**Pull request by kadamwhite**
**`--standalone` isn't**

Browserify's "Standalone" option is poorly named, as `--standalone`- generated bundles cannot be consumed within any other project that is build using browserify. The reason this is the case is that Browserify tries to parse any "require" calls that it finds in the source.

However, once Browserify has been used to build p5, those are not Node's `require` method anymore: they are an internal method defined within the bundled code. Browserify trips over itself by misinterpreting the purpose of the `require`s that it generated when we created the bundle.

[derequire](https://github.com/calvinmetcalf/derequire) is designed to solve this problem: it re-writes the generated bundle code to change all instances of "require" into "_dereq_". This "hides" them from subsequent runs of Browserify, and permits the library to be loaded as intended.

[Browserify issue 1151](https://github.com/substack/node-browserify/issues/1151) has more discussion of this issue, including a movement to implement the "derequire" behavior by default when using `--standalone`, which would (subjectively) make the flag function more predictably.

**Grunt changes**

Because `derequire` is designed either to function fully by use of its programmatic API, or fully from the command line, I was not able to get it integrated into the existing Grunt-Browserify task. Instead, I have written a new, bespoke Grunt task that will

- Read the source code into Browserify (with appropriate transforms)
- Run the bundled code through `derequire` to re-write the "require"s
- Prepend the same code comment banner we have been using
- Save the processed code to a file as `lib/p5.js`

This task lives in `build/tasks/browserify.js`, using the (that is to say, my) recommended approach of splitting more complex grunt tasks out into individual files for easier readability and maintenance.

This task runs slightly slower than the older `grunt-browserify` task, which I believe to be unavoidable due to the additional code processing that is required to make the build browserifiable.

A note on Webpack: I investigated using Webpack to create the bundle, as Webpack's UMD build target does not seem to share Browserify's `--standalone` quirks. For now we believe that adding Webpack would introduce more complexity and maintenance overhead than it removed,
however, so I opted for the custom Grunt task approach.

**Unresolved Issues**

This does nothing to address #785: we will likely need to adapt the browserify task to generate separate source builds for `p5.js` and `p5.min.js` before we can conditionally stub out behavior.

**Resolved Issues**

This fixes #818: I have copied the generated code into the [example repository](https://github.com/geekydatamonkey/test-p5-browserify) provided by @geekydatamonkey, and `browserify main.js -o bundle.js` worked as expected.

However, more testing is appreciated: use this branch to `grunt build` or `npm run build`, then copy the generated `lib/p5.js` file into a browserify project and see if it works or not.

**Review Requested**

Pinging @tbranyen for feedback on this implementation!

### CODE REVIEW

**Comment by kadamwhite** [comment]
@lmccart does this look ok to you? Any questions or concerns?

**Comment by lmccart** [comment]
This is great @kadamwhite, thanks for such thorough research and explanation! With admittedly limited familiarity with browserify, reading through your comments and code, all looks good to me. My only question is whether the [existing browserify entry](https://github.com/kadamwhite/p5.js/blob/build/fix-browserify-woes/Gruntfile.js#L166) in the gruntfile is redundant or unnecessary with your added task? I see some of the same lines written in both places and this seems like it could be confusing for someone trying to modify any of this later.

**Comment by kadamwhite** [comment]
@lmccart That is definitely not-needed, thanks for the catch!

File: build/tasks/browserify.js [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+var path = require('path');
+var fs = require('fs');
+var browserify = require('browserify');
+var derequire = require('derequire'); // This is a silly thing to type
+
+var bannerTemplate = '/*! p5.js v<%= pkg.version %> <%= grunt.template.today("mmmm dd, yyyy") %> */';
+
+module.exports = function(grunt) {
+
+  var libFilePath = path.join(process.cwd(), 'lib/p5.js');
```
Comment (mzgoddard) [inline build/tasks/browserify.js]: Use [path.resolve](https://nodejs.org/docs/v0.8.0/api/path.html#path_path_resolve_from_to)?

File: build/tasks/browserify.js [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+    // Then read the bundle into memory so we can run it through derequire
+    bundle.on('data', function(data) {
+      code += data;
+    }).on('end', function() {
+      // "code" is complete: create the distributable UMD build by running
+      // the bundle through derequire, then write the bundle to disk.
+      // (Derequire changes the bundle's internal "require" function to
+      // something that will not interfere with this module being used
+      // within a separate browserify bundle.)
+      fs.writeFile(libFilePath, derequire(code), done);
```
Comment (mzgoddard) [inline build/tasks/browserify.js]: Use [grunt.file.write](http://gruntjs.com/api/grunt.file#grunt.file.write)?

Comment (mzgoddard) [inline build/tasks/browserify.js]: Log that `libFilePath` was written with [grunt.log.writeln](http://gruntjs.com/api/grunt.log#grunt.log.writeln-grunt.verbose.writeln)?

Example:
https://github.com/gruntjs/grunt-contrib-concat/blob/master/tasks/concat.js#L116-L117

**Comment by kadamwhite** [comment]
I was hesitant to use the grunt utilities because I envisioned keeping the code fairly build-system-agnostic, but I suppose that's essentially meaningless unless I abstracted this out into its own module, anyway.

Good call on the log message, as well; the existing browserify plugin notified on bundle creation:
image
so I will follow that lead.

**Comment by lmccart** [comment]
cool, just let me know when any last tweaks have been made and it's ready for merge!

**Comment by tbranyen** [comment]
:+1:

**Comment by kadamwhite** [comment]
@lmccart This should be ready now! Let me know if it causes any problems for you when you run it locally.

**Comment by ujjwalsahay** [comment]
@lmccart  please check your mail i have mailed you regarding p5 ebook contribution

**Comment by lmccart** [comment]
@kadamwhite hm looks like a test is failing, any thoughts? i'll take a look later today if you don't get a chance.

**Comment by kadamwhite** [comment]
Aha, I know why this is occurring; I will fix it later this evening.

File: build/tasks/browserify.js (hunk 1 above)
Comment (kadamwhite) [inline build/tasks/browserify.js]: Used `require.resolve` for the `srcFilePath` app entry point, and `path.resolve` for the `libFilePath` build destination file (which will not yet exist until built in a clean environment, causing `require.resolve` to fail)

**Comment by kadamwhite** [comment]
@lmccart Should be all set now

**Comment by lmccart** [comment]
fantastic, thank you!!
