### PR TITLE
fixed repeated key presses when a modifier key is held

### LINKED ISSUE #7282: Repeated key presses when a modifier key is held do not fire events
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [X] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

1.10.0

### Web browser and version

Firefox, Chrome

### Operating system

MacOS

### Steps to reproduce this

The goal here was to have a custom undo handler using the meta key. A single meta-z should be handled, but also holding the meta key and repeatedly hitting the z key should also fire. On my mac, I'm finding that this works for the first press but not repeated presses:

```js
function setup() {
  createCanvas(400, 400);
}

function keyPressed(event) {
  if (event.metaKey && event.keyCode === 90) {
    console.log('undo')
    return false
  }
}
```

Meanwhile, doing it with vanilla js does work:
```js
function setup() {
  createCanvas(400, 400);
  document.addEventListener('keydown', function(event) {
    if (event.metaKey && event.keyCode === 90) {
      console.log('undo')
      event.stopPropagation()
    }
  })
}
```

Narrowing it down, it looks like the key up event [isn't firing after the first meta-z](https://editor.p5js.org/davepagurek/sketches/BQ2Lmicii) if I release the z but hold the meta key. I'm not sure yet why that is, but because of that, `this._downkeys` isn't getting reset to false, so I suspect the second event isn't getting fired because of this condition:
https://github.com/processing/p5.js/blob/e9ee594421f02b0659c0c04c1d8ee0de284127b7/src/events/keyboard.js#L443-L447

### PR DESCRIPTION
**Pull request by Rishab87**
Resolves #7282 

 Changes:
As @davepagurek proposed above, I have used .repeat check to make sure we can capture repeated presses and recording which keys were pressed in combination with the meta key, and then when the meta key is released, manually update _downkeys so that they're all set to false

 Screenshots of the change:

img

#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

File: src/events/keyboard.js [hunk 1]
```diff
@@ -615,18 +626,21 @@ p5.prototype._onkeydown = function(e) {
...
 p5.prototype._onkeyup = function(e) {
+  this._setProperty('isKeyPressed', false);
+  this._setProperty('keyIsPressed', false);
+  this._setProperty('_lastKeyCodePressed', this._keyCode);
   this._downKeys[e.which] = false;
 
-  if (!this._areDownKeys()) {
-    this._setProperty('isKeyPressed', false);
-    this._setProperty('keyIsPressed', false);
+  if (e.which === 91 || e.which === 93) { // Meta key codes
```
Comment (davepagurek) [inline src/events/keyboard.js:634]: On my mac, the left meta key generates code 224, so this branch never gets executed. Is there a reason for using `e.which` over checking if `e.key === 'Meta'`?

Comment (Rishab87) [reply src/events/keyboard.js]: no their wasn't any specific reason for using e.which, really sorry I have changed it to check for e.key === 'Meta' for consistency accross different platforms

**Review by davepagurek — APPROVED** [review]
I think these changes look good to merge, thank you @Rishab87!

Next time, we ask that you wait to be assigned to an issue before filing a PR, as for this one someone else had been assigned. Our [contributor docs](https://github.com/processing/p5.js/blob/main/contributor_docs/contributor_guidelines.md#introduction) mention:
> You should not "jump the queue" by filing a PR for an issue that either someone else has indicated willingness to submit a contribution or has already been assigned to someone else.

**Comment by Rishab87** [comment]
> time, we ask that you wait to be assigned to an issue before filing a PR, as for this one someone else had been assigned.

@davepagurek sure thing! I'll keep that in mind from next time!
