### PR TITLE
Correct msgWithReference logic in FES to fix issue 5576

### LINKED ISSUE #5576: Incorrect link to reference in FES in p5.[Class] errors
### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Other (specify if possible)

### p5.js version

1.4.0

### Web browser and version

_No response_

### Operating System

_No response_

### Steps to reproduce this

In the event of an error in any method in any p5.[class] object, the reference link provided by the FES is wrong.

p5.[class] refers to classes like `p5.File`, `p5.Graphics`, `p5.Font`, etc.

Examples:

image

For the above, the reference link should be https://p5js.org/reference/#/p5.File/file rather than https://p5js.org/reference/#/p5/File

image

For the above, the reference link should be https://p5js.org/reference/#/p5.Graphics rather than https://p5js.org/reference/#/p5/Graphics

This issue is also present in p5.Font as mentioned in issue #5346.

I am working on this issue. However, I am not too familiar with the Friendly-Error System, so any pointers and help will be highly appreciated.

### PR DESCRIPTION
**Pull request by Ayush23Dash**
Resolves [#5576 ]

 Changes:

Whenever a function having p5.[Class] in its name encounters an error, we need to have the a different FES error link as compared to when a different p5 function name encounters error.
This issue fixes #5576 

 Screenshots of the change:

Screenshot 2023-06-19 at 12 33 01 AM

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by nbriz** [comment]
@Ayush23Dash the change u made makes sense + looks good to me as far as i can tell.

that said, when testing this locally i noticed something potentially off. first i tested issue #5576 by reproducing it locally using the version of p5.js i had cloned at the start of GSoC, as expected i got the same error reported in the issue with the link to the wrong doc: 

```
🌸 p5.js says: [sketch.js, line 6] An error with message "file.type is undefined" occurred inside the p5js library when File was called. If not stated otherwise, it might be an issue with the arguments passed to File. (http://p5js.org/reference/#/p5/File)
```

looking at ur code it seems like a great way to fix the issue, but just to do my due diligence i pulled ur changes to my local machine, built the library (`npm run build`) and re-ran the test sketch to see if the URL was pointing to the right doc, but to my surprise I got an entirely different error message:

```
🌸 p5.js says: 
[p5-test.js, line 259076] Cannot read property of undefined. Check the line number in error and make sure the variable which is being operated is not undefined.

 + More info: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_access_property#what_went_wrong p5-test.js:109297:18
┌[http://localhost:8000/p5.js/lib/p5-test.js:259076:54] 
	 Error at line 259076 in File()
└[http://localhost:8000/FES_TESTER/sketch.js:6:11] 
	 Called from line 6 in setup()
```

realizing that the changes i pulled included a lot more than the change u had made (because it had been a couple of weeks since i pulled from upstream) I then ran the same experiment with the latest main branch and got the same result. 

@almchung any idea why this is the case? i'm assuming what we would want to see in the console is something more like this right?
```
🌸 p5.js says: [sketch.js, line 6] An error with message "file.type is undefined" occurred inside the p5js library when File was called. If not stated otherwise, it might be an issue with the arguments passed to File. (http://p5js.org/reference/#/p5.File)
```

**Comment by Ayush23Dash** [comment]
Thanks for the thorough update @nbriz. This seems like a weird issue, I will check in and then discuss it over our meet!

**Comment by nbriz** [comment]
hey @Qianqianye + @almchung i just finished meeting with @Ayush23Dash && as mentioned in my previous comment it seems like there have been changes elsewhere in the code base that prevent me/us from fully testing Ayush's change, but I'm fairly certain the change made would solve issue #5576 so my recommendation would be to merge this && close that issue. 

is that something I should do myself, or is that something u'll do @Qianqianye  (i'm still learning the workflow + protocols 😅)

**Comment by Qianqianye** [comment]
Thanks @nbriz! I have added you to the list of contributors who can merge PRs directly, so please feel free to go ahead and merge this one. You can read more about the workflow in the [steward guide](https://github.com/processing/p5.js/blob/main/contributor_docs/steward_guidelines.md). I also pasted the PR merge workflow below:

> Once the PR has been reviewed and no additional changes are required, a steward can mark the PR as "Approved" by choosing the "Approve" option in the previous step (instead of "Comment" or "Request changes") with or without additional comments. The steward can then either request additional review by another steward or maintainer if desired, or merge the PR if they have merge access or a maintainer will merge the approved PR.

**Comment by Ayush23Dash** [comment]
Hey @Qianqianye @nbriz 
Just one final question regarding this : Should I squash and rebase the commit before Nick merges it?
Or we can merge it as it is!?

File: src/core/friendly_errors/fes_core.js [hunk 1]
```diff
@@ -142,7 +142,11 @@ if (typeof IS_MINIFIED !== 'undefined') {
 
       const funcName =
         methodParts.length === 1 ? func : methodParts.slice(2).join('/');
-      msgWithReference = `${message} (http://p5js.org/reference/#/${referenceSection}/${funcName})`;
+
+      //Whenever func having p5.[Class] is encountered, we need to have the error link as mentioned below else different link
+      funcName.substring(0,2) === 'p5.' ?
```
Comment (wuyudi) [inline src/core/friendly_errors/fes_core.js:147]:
```js
funcName.startsWith('p5.') ?
```

Comment (nbriz) [reply src/core/friendly_errors/fes_core.js:147]: oh wow! when was [this method ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith) added to JS strings? don't think i'd seen it before. thnx @wuyudi  

it's not completely necessary, but it would be easier for other contributors to read/understand, what do u think @Ayush23Dash

**Comment by nbriz** [comment]
ah! thnx for pointing me to the steward guide @Qianqianye  just read through it (makes perfect sense), only question i have is where do i call the "all-contributors"? is that a comment i should leave here in the PR (before or after it's closed? does it matter?) or somewhere else?

@Ayush23Dash as far as I can tell from looking at the [rebase and resolve conflicts](https://github.com/processing/p5.js/blob/main/contributor_docs/contributor_guidelines.md#rebase-and-resolve-conflicts) in the contributor guidelines, nothing more is needed git-wise (seeing as there are no conflicts && only the necessary files were changed + commits made) but considering that this is our first GSoC FES PR, i'll let @Qianqianye  confirm this before i merge :)

File: src/core/friendly_errors/fes_core.js (hunk 1 above)
Comment (Ayush23Dash) [reply src/core/friendly_errors/fes_core.js:147]: We can use this @nbriz! Thanks @wuyudi, Ill just update the PR

File: src/core/friendly_errors/fes_core.js [hunk 2]
```diff
@@ -144,7 +144,7 @@ if (typeof IS_MINIFIED !== 'undefined') {
         methodParts.length === 1 ? func : methodParts.slice(2).join('/');
 
       //Whenever func having p5.[Class] is encountered, we need to have the error link as mentioned below else different link
-      funcName.substring(0,2) === 'p5.' ?
+      funcName.startsWith(0,2) === 'p5.' ?
```
Comment (nbriz) [inline src/core/friendly_errors/fes_core.js:147]: did u test this? i think the first argument of [startsWidth](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith) needs to be a string

Comment (Ayush23Dash) [reply src/core/friendly_errors/fes_core.js]: Apologies, fixed and tested it as well now!

**Comment by almchung** [comment]
> 

Thank you so much for taking care of this issue! 
@nbriz - To use the all-contributors bot, you can add a comment with the `@all-contributors please add  [...]` command to this thread https://github.com/processing/p5.js/issues/2309 or to any other issue tickets or posts (including this PR I suppose).

**Comment by nbriz** [comment]
ok @Qianqianye @almchung @Ayush23Dash @wuyudi merging our first FES-GSoC-2023 PR! 🥳

@all-contributors please add @Ayush23Dash for code
@all-contributors please add @nbriz for review

**Comment by Qianqianye** [comment]
@all-contributors please add @Ayush23Dash for code

**Comment by Qianqianye** [comment]
@all-contributors please add @nbriz for review

**Comment by Qianqianye** [comment]
@all-contributors please add @Ayush23Dash for code

**Comment by Qianqianye** [comment]
Thank you all for working on this. There was a small error in the allcontributors doc earlier. I just added both @Ayush23Dash and @nbriz! 🎉
