### PR TITLE
Update environment.js with fix for frameRate description

### LINKED ISSUE #6013: frameRate() doesn't accurately report frame rate, it is the drawRate
### Most appropriate sub-area of p5.js?

- [X] Core/Environment/Rendering

### p5.js version

1.5.0 (but also all)

### Web browser and version

Any

### Operating System

Any

### Steps to reproduce this

This may not be considered a bug that y'all would want to fix in p5.js but I at least wanted to point out that it's inaccurate to refer to the result of the p5.js `frameRate()` function as a measure of FPS, like it is on this page:

https://github.com/processing/p5.js/wiki/Optimizing-p5.js-Code-for-Performance#frames-per-second-fps

It's also not correct to say "Calling `frameRate()` with no arguments returns the current framerate." which is on the reference page:

https://p5js.org/reference/#/p5/frameRate

Here's the reasons why.

EDIT:

I want to try summarizing the issue again. If a sketch's fps is high enough for it to display at 60hz completely stable, verifiable in Chrome's dev tools, `frameRate()` will still not return 60 every time. Hence, it does not report the refresh rate of the sketch. It's actually a calculation of the difference in time between when `requestAnimationFrame` runs the draw function and the previous time it did so. As far as I understand that's not always the same amount of time even if the frame rate always matches the computer display's refresh rate or target frame rate set in p5.js. So even if frames are always drawn on time `frameRate()` changes because there's some variation in the browser's delay between when a frame is drawn and when `requestAnimationFrame` runs its callback function. This makes the value `frameRate()` returns kind of random, which can be seen in the example sketch I made. Yet, because it roughly will keep time with the real frame rate, though on average it loses time, even though its values are not technically useful for performance testing, `frameRate()` values are useful visually as @davepagurek pointed out.

The name of `frameRate()` is therefore technically a misnomer because it doesn't return values that are accurate by common definition or the gaming community definition. I think ironically `drawRate` is an accurate name for it since it actually measures the rate between draw function calls and does not measure the frame rate by common definition. I did some research and with JS I think there's no way to get an accurate report of the actual frame rate of a sketch, which can only be viewed in browser dev tools after a profile recording is finished. Even if `frameRate` is not changed this info should be included in its documentation.

Calculating accurate FPS (gaming definition) is definitely possible though, as it's just the time one frame takes to render, not including any delays. I've included a function in p5play called `getFPS()` to make this kind of performance testing more accessible.

ORIGINAL POST:

FPS, in the context of performance testing, is typically a measure of how many frames renders could fit in one second if the code responsible for rendering a frame was run without delays, so it shouldn't be capped by the target frame rate or monitor refresh rate. 

FPS should be calculated by subtracting the time immediately after a frame is drawn from the time immediately before its drawn. Whether a program is running slower or faster than the target frame rate, that result should be reflected in the FPS calculation.

The p5.js `frameRate()` function is calculated by including the delay between frames, capping the measure to roughly the target frame delay. So it only returns a roughly accurate measure of FPS if the current frame rate is below the target frame rate. If p5 finishes running the pre draw functions, the draw function, and post draw functions before the delay allotted by the target frame rate, then the remaining delay between draw calls is included in the `frameRate()` calculation. If the sketch is running at a stable 60fps, which can be verified in the chrome dev tools, then `frameRate()` should just return 60 every time, but it doesn't. It returns wildly inaccurate values ranging from as low as 53 to as high as 68 in my testing. If there's some good reason for this which I can't think of, please let me know.

When a sketch is running at a stable 60fps, `frameRate()` returns a value that isn't a useful measure of the real frame rate or the FPS.

### PR DESCRIPTION
**Pull request by quinton-ashley**
Resolves #6013

 Changes:
Changes frameRate description to make it more accurate.

 Screenshots of the change:

 Calling <a href="#/p5/frameRate">frameRate()</a> with no arguments or
 with arguments that are not of type Number or are non-positive returns
 an approximation of the current frame rate. The draw function must run at
 least once before it will return a value. This is the same as using
 <a href="#/p5/getFrameRate">getFrameRate()</a>.
 
 The returned frame rate value is technically the rate at which the draw 
 function is called per second. This value can vary wildly, even if the 
 actual display rate achieved is consistent. To accurately test the
 performance of your sketches, use your browser's performance profiling tools.

### CODE REVIEW

File: src/core/environment.js [hunk 1]
```diff
@@ -246,12 +246,18 @@ p5.prototype.cursor = function(type, x, y) {
...
- * the current framerate. The draw function must run at least once before it will
- * return a value. This is the same as <a href="#/p5/getFrameRate">getFrameRate()</a>.
- *
- * Calling <a href="#/p5/frameRate">frameRate()</a> with arguments that are not
- * of the type Number or are non-positive also returns current framerate.
+ * Calling <a href="#/p5/frameRate">frameRate()</a> with no arguments or
+ * with arguments that are not of type Number or are non-positive returns
+ * an approximation of the current frame rate. The draw function must run at
+ * least once before it will return a value. This is the same as using
+ * <a href="#/p5/getFrameRate">getFrameRate()</a>.
```
Comment (davepagurek) [inline src/core/environment.js:253]: Just noticed that this link is dead (possibly because this method is private?) https://github.com/processing/p5.js/blob/8e117ae3dd1ac44f8e42bcd1d350a4cde6c36b05/src/core/environment.js#L318-L321

We can decide later to take this out if we want, but for now maybe we should at least take out the link (similar to how `setFrameRate` is documented on line 247.)

File: src/core/environment.js [hunk 2]
```diff
@@ -246,12 +246,18 @@ p5.prototype.cursor = function(type, x, y) {
...
+ *
+ * The returned frame rate value is technically the rate at which the draw 
+ * function is called per second. This value can vary wildly, even if the 
+ * actual display rate achieved is consistent. To accurately test the
```
Comment (davepagurek) [inline src/core/environment.js:257]: It might be a bit confusing to readers describing the display rate achieved, as the display rate of the monitor is likely fixed and not related to the sketch, and the draw rate of the sketch itself is what `frameRate()` returns. Do you mean that the speed at which the code in the `draw` function executes can be constant? How would you feel about saying something like this: "Even if the code in `draw()` takes a consistent amount of time to run, the value of `frameRate()` can vary from frame to frame as p5 attempts to achieve a target frame rate on average."

File: src/core/environment.js [hunk 3]
```diff
@@ -246,12 +246,18 @@ p5.prototype.cursor = function(type, x, y) {
...
- *
- * Calling <a href="#/p5/frameRate">frameRate()</a> with arguments that are not
- * of the type Number or are non-positive also returns current framerate.
+ * Calling <a href="#/p5/frameRate">frameRate()</a> with no arguments or
+ * with arguments that are not of type Number or are non-positive returns
+ * an approximation of the current frame rate. The draw function must run at
+ * least once before it will return a value. This is the same as using
+ * <a href="#/p5/getFrameRate">getFrameRate()</a>.
+ *
+ * The returned frame rate value is technically the rate at which the draw
```
Comment (davepagurek) [inline src/core/environment.js:255]: Btw just a heads up, I think the tests are failing due to some trailing spaces here and on a few other lines.

**Review by davepagurek — COMMENTED** [review]
Thanks for taking this on! Sorry for the delay, just got back from a small vacation. Just a few wording suggestions!

**Comment by quinton-ashley** [comment]
All good! But your edit is inaccurate and doesn't reflect what I'm trying to convey: "Even if the code in draw() takes a consistent amount of time to run, the value of frameRate() can vary from frame to frame as p5 attempts to achieve a target frame rate on average."

My goal here is to assure users that even though `frameRate()` always churns out a wild range of numbers, because it's method of calculating the frameRate is inaccurate, even though their sketch might not just be attempting to achieve the target frame rate on average, but always achieving the target frame rate. For people concerned with performance (mainly game devs) there is a big difference between sometimes hitting 60fps and always hitting 60fps. The speed at which the draw function executes is never consistent, even if the display rate (actual frame rate) achieved is consistent.

To me, the way I phrased the problem is a concise and accurate, without bogging down users with too much detail. I don't think the reference documentation needs a full detailed description of the problem, it should just give users a general idea. If you'd like I could add a "For more info see this blog post" link to a more complete explanation of the issue. Or if you'd like you can give another suggestion on how to rephrase it. I can't think of any way to phrase it better. It may just be confusing because it's a convulted concept to wrap one's head around.

**Comment by davepagurek** [comment]
I think my issue is mostly that introducing a term like "display rate" might add some more ambiguity since we don't define it, and it's such a similar term. I was hoping that explaining what part leads to the inaccuracy might help with that, but I can see how that might be trying to pack too much into the reference. Would you feel better about it if it was something slightly simpler that still avoids the new terms? Like: "Even if the code in draw() takes a consistent amount of time to run, the value of frameRate() can vary from frame to frame. To accurately test ..."

**Comment by quinton-ashley** [comment]
@davepagurek Just updated the pr and it passes all checks now :) Thank you for your help on this.

**Review by davepagurek — APPROVED** [review]
Thanks for the updates!
