### PR TITLE
Fix/webgpu crash pixel density

### LINKED ISSUE #8456: [p5.js 2.0 Bug Report]: WebGPU: can't call pixelDensity(1) after setAttributes
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [x] Other (specify if possible)

### p5.js version

2.2.0-rc.6

### Web browser and version

144.0.7559.60 (Official Build) (arm64)

### Operating system

MacOS Sonoma 14.6.1

### Steps to reproduce this

I've provided a sketch that tries to (in order)...:
1. `createCanvas` with webgpu renderer
2. call `setAttributes`
3. call `pixelDensity(1)`

### Steps:
1. visit and run https://editor.p5js.org/neill0/sketches/iiIdcxoAz
2. see stack trace in console (included below)
3. see pixel density has NOT been set to 1 (in console report) 
4. switch out the renderer to use WEBGL instead of WEBGPU
5. re-run the sketch
6. observe all works fine

### stack trace

```
Cannot read properties of undefined (reading 'createTexture')
    at RendererWebGPU._updateSize
    at RendererWebGPU.resize
    at RendererWebGPU.resize
    at fn.resizeCanvas
    at p5.resizeCanvas
    at fn.pixelDensity
    at p5.pixelDensity
    at setup
```

### Snippet:
This is just a copy of the live code at https://editor.p5js.org/neill0/sketches/iiIdcxoAz
```js
async function setup() {
  
  // const renderer = WEBGL; // this works
  const renderer = WEBGPU ?? "webgpu";

  const canvas = await createCanvas(400, 400, renderer);
  
  setAttributes({ alpha: false, antialias: true });
  
  pixelDensity(1);

  console.log("pixel density: " + pixelDensity())
  console.log("VERSION: " + VERSION)
  console.log("renderer: " + renderer)
}

function draw() {
  background("orange");
  sphere(100);
}
```

### alternative: trying to call setAttributes BEFORE createCanvas

Until v2.2.x it's been possible to call `setAttributes` before calling `createCanvas`, which might have worked as a workaround for the above.  

However, that doesn't seem possible now - it errors with 
```
this._renderer._setAttributes is not a function
```
both under WEBGPU and WEBGL.  (Maybe it's by design).

### PR DESCRIPTION
**Pull request by saurabh24thakur**
Fixes #8456 

# Description
Fixes a crash when using the WebGPU renderer where calling [pixelDensity()](cci:1://file:///e:/code%20_zone/openSource/p5.js-GSOC/src/core/environment.js:889:2-960:4) immediately after [setAttributes()](cci:1://file:///e:/code%20_zone/openSource/p5.js-GSOC/src/webgpu/p5.RendererWebGPU.js:2656:2-2659:3) (or any other function that triggers an asynchronous context reset) would result in `TypeError: Cannot read properties of undefined (reading 'createTexture')`.

### The Issue
In p5.js 2.0, [setAttributes()](cci:1://file:///e:/code%20_zone/openSource/p5.js-GSOC/src/webgpu/p5.RendererWebGPU.js:2656:2-2659:3) triggers an asynchronous reset of the rendering context via [_resetContext()](cci:1://file:///e:/code%20_zone/openSource/p5.js-GSOC/src/core/p5.Renderer3D.js:335:2-404:3). Because core functions like [pixelDensity()](cci:1://file:///e:/code%20_zone/openSource/p5.js-GSOC/src/core/environment.js:889:2-960:4) are synchronous, they can trigger a [resize()](cci:1://file:///e:/code%20_zone/openSource/p5.js-GSOC/src/core/p5.Renderer.js:279:2-285:3) (and subsequently [_updateSize()](cci:1://file:///e:/code%20_zone/openSource/p5.js-GSOC/src/webgpu/p5.RendererWebGPU.js:158:4-175:5)) on a new renderer instance before its WebGPU device has been successfully initialized.

### Changes
1.  **RendererWebGPU**: Added guard clauses to [_updateSize()](cci:1://file:///e:/code%20_zone/openSource/p5.js-GSOC/src/webgpu/p5.RendererWebGPU.js:158:4-175:5), [clear()](cci:1://file:///e:/code%20_zone/openSource/p5.js-GSOC/src/webgpu/p5.RendererWebGPU.js:177:4-228:5), and [clearDepth()](cci:1://file:///e:/code%20_zone/openSource/p5.js-GSOC/src/webgpu/p5.RendererWebGPU.js:230:4-271:5) to return early if `this.device` is not yet defined. Since [_initContext()](cci:1://file:///e:/code%20_zone/openSource/p5.js-GSOC/src/webgpu/p5.RendererWebGPU.js:83:4-107:5) calls these methods upon successful initialization, the state is eventually synchronized correctly once the device is ready.
2.  **Renderer3D**:
    *   Updated [_resetContext()](cci:1://file:///e:/code%20_zone/openSource/p5.js-GSOC/src/core/p5.Renderer3D.js:335:2-404:3) to `await` the new renderer's `contextReady` promise **before** replacing the existing renderer on the p5 instance. This ensures that the sketch's `_renderer` property always points to a valid, initialized renderer.
    *   Ensured the new renderer inherits the [pixelDensity](cci:1://file:///e:/code%20_zone/openSource/p5.js-GSOC/src/core/environment.js:889:2-960:4) of the renderer it is replacing to avoid size-mismatch warnings in the console (e.g., depth-stencil attachment size mismatches).
3.  **Tests**: Added a new unit test in [test/unit/webgpu/issue_repro.js](cci:7://file:///e:/code%20_zone/openSource/p5.js-GSOC/test/unit/webgpu/issue_repro.js:0:0-0:0) that specifically reproduces this race condition.

## Checklist
- [x] I have read the [CONTRIBUTING](https://github.com/processing/p5.js/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

File: test/unit/webgpu/issue_repro.js [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+          };
+        });
+      } catch (err) {
+        reject(err);
+      }
+    });
+
+    // If we reach here, no immediate crash occurred.
+    // Let's wait for the context to finish resetting to be sure everything is stable.
+    await new Promise(resolve => setTimeout(resolve, 100));
```
Comment (davepagurek) [inline test/unit/webgpu/issue_repro.js]: Timeouts in tests are fairly brittle, we can use `expect(() => { ... }).not.toThrow()` or something like that as an alternative.

File: test/unit/webgpu/issue_repro.js [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+    // This test simulates the issue where a synchronous call (pixelDensity)
+    // happens before an asynchronous initialization (setAttributes -> _resetContext)
+    // is complete.
+    
+    await new Promise((resolve, reject) => {
+      try {
+        myp5 = new p5(function(p) {
+          p.setup = async function() {
+            try {
+              await p.createCanvas(100, 100, 'webgpu');
```
Comment (davepagurek) [inline test/unit/webgpu/issue_repro.js]: Can we use `p.WEBGPU` rather than the value of the constant?

File: test/unit/webgpu/issue_repro.js [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+              
+              // This triggers an asynchronous _resetContext
+              p.setAttributes({ powerPreference: 'low-power' });
```
Comment (davepagurek) [inline test/unit/webgpu/issue_repro.js]: I'm not 100% sure that we'll do something with this, can we try changing `antialias` as a more normal example?

File: test/unit/webgpu/issue_repro.js [hunk 4]
```diff
@@ -0,0 +1,51 @@
+import p5 from '../../../src/app.js';
```
Comment (davepagurek) [inline test/unit/webgpu/issue_repro.js]: A new file called `issue_repro.js` is not really readable for future contributors trying to understand the structure of our code and tests. Could this just be a test in the existing WebGPU renderer tests?

File: src/webgpu/p5.RendererWebGPU.js [hunk 5]
```diff
@@ -157,6 +157,7 @@ function rendererWebGPU(p5, fn) {
     }
 
     _updateSize() {
+      if (!this.device) return;
```
Comment (davepagurek) [inline src/webgpu/p5.RendererWebGPU.js]: To clarify, is this added just to methods that get called automatically when you reinitialize the context?

**Comment by davepagurek** [comment]
Thanks for working on this! Left a few comments, let me know what you think!

**Comment by saurabh24thakur** [comment]
Thanks for the review, @davepagurek  Those points make total sense. I'll move the test into the main WebGPU suite and swap out the setTimeout for a cleaner expect().not.toThrow() assertion. I’ll also update the test to use p.WEBGPU and antialias as you suggested. I'll double-check the guard clause scoping and push the updates shortly!

**Review by davepagurek — APPROVED** [review]
Thanks for making those changes, looks great!

**Comment by davepagurek** [comment]
@all-contributors please add @saurabh24thakur for code, test
