### PR TITLE
Fix for touchEnded triggers twice among other issues with touchEnded/mouseReleased on mobile

### LINKED ISSUE #6737: touchEnded triggers twice among other issues with touchEnded/mouseReleased on mobile
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [X] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.9.0

### Web browser and version

120.0.6099.210

### Operating System

Android

### Steps:
1. Have touchEnded() or mouseReleased() on mobile

Here's a sketch demonstrating it
https://editor.p5js.org/PotatoBoy/sketches/MTUuPrS8T

On touchscreen
- mouseReleased and touchEnded both trigger if they're both present (same for mouseReleased)
- If either is without the other it triggers twice

### PR DESCRIPTION
**Pull request by RandomGamingDev**
Resolves #6737

 Changes:

Adds an instance variable called touchend to p5 and changed p5.prototype._ontouchend & p5.prototype._onmouseup to function as documented.

On touchscreen
- mouseReleased and touchEnded no longer both trigger if they're both present (same for mouseReleased)
- If either is without the other it doesn't triggers twice anymore

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

File: src/events/mouse.js [hunk 1]
```diff
@@ -731,6 +731,11 @@ p5.prototype._onmouseup = function(e) {
   const context = this._isGlobal ? window : this;
   let executeDefault;
   this._setProperty('mouseIsPressed', false);
+
+  if (this.touchend) {
```
Comment (davepagurek) [inline src/events/mouse.js:735]: Does this get called implicitly because the browser triggers a mouse event after the touch event? It'd be helpful adding a comment here explaining if so.

**Comment by davepagurek** [comment]
I think this looks good to me, but could an events steward with more familiarity with the control flow double check? @limzykenneth, @richardegil, @angelabelle, @littlejacinthe, @TanviKumar, @tuminzee

File: src/events/mouse.js (hunk 1 above)
Comment (RandomGamingDev) [reply src/events/mouse.js:735]: I'll add a comment for this and the other PR

Comment (RandomGamingDev) [reply src/events/mouse.js:736]: I've added the comment

**Comment by RandomGamingDev** [comment]
> I think this looks good to me, but could an events steward with more familiarity with the control flow double check? @limzykenneth, @richardegil, @angelabelle, @littlejacinthe, @TanviKumar, @tuminzee

Could you guys also check it this sorta thing happens to any of the other events for touchscreens? The fact that this happened twice #6740 might mean that this sorta issue's in other event handlers that deal with touch as well.

**Comment by Garima3110** [comment]
Hello everyone, I just want to add that I did the tests for this  on Safari, and it all looks good. I also tried it out on Chrome on my Android phone, and Safari on my iPhone behaved the same way. So, it seems like things are working fine on both browsers.

**Review by davepagurek — APPROVED** [review]
Thanks for testing this out! I'm going to merge this in now that we've confirmed it also works as expected in different platforms.
