### PR TITLE
Fixed cursor image issue

### LINKED ISSUE #6804: cursor() - the image not displayed as the cursor
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [X] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [X] Other (specify if possible)

### p5.js version

1.9.0

### Web browser and version

Google Chrome 121.0.6167.139

### Operating system

Mac

### Steps to reproduce this

reference to https://p5js.org/reference/#/p5/cursor

`If the path to an image is passed, as in cursor('assets/target.png'), then the image will be used as the cursor`

acctually the image is not used as the cursor 

I tested 

cursor(CROSS) is working
cursor('https://avatars0.githubusercontent.com/u/1617169?s=16')  is working

BUT  cursor("assets/erasers/64-eraser.png") is NOT working

### PR DESCRIPTION
**Pull request by haroon10725**
Resolves #6804

https://github.com/processing/p5.js/assets/104259212/890a427a-fea5-46e2-94de-a36f3a141a36

Hey @davepagurek, PR is ready for review. The only problem was that user did not know pixel size for image, that's why it was not rendering the cursor image. So I have updated the reference page of cursor.

Resolves #[Add issue number here]

 Changes:

 Screenshots of the change:

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

File: src/core/environment.js [hunk 1]
```diff
@@ -199,7 +199,7 @@ p5.prototype.focused = document.hasFocus();
  * strings: `'help'`, `'wait'`, `'crosshair'`, `'not-allowed'`, `'zoom-in'`,
  * and `'grab'`. If the path to an image is passed, as in
  * `cursor('assets/target.png')`, then the image will be used as the cursor.
- * Images must be in .cur, .gif, .jpg, .jpeg, or .png format.
+ * Images must be in .cur, .gif, .jpg, .jpeg, or .png format and should be of 32 by 32 pixels dimensions.
```
Comment (davepagurek) [inline src/core/environment.js:202]: Thanks for finding this limit, I wasn't aware of it! I found a source for the limit on MDN, how do you feel about linking to it?

```suggestion
 * Images must be in .cur, .gif, .jpg, .jpeg, or .png format and should be <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#icon_size_limits">at most 32 by 32 pixels large.</a>
```

Comment (haroon10725) [reply src/core/environment.js:202]: Yes we can link to it.

Comment (haroon10725) [reply src/core/environment.js:202]: Hey, I think we should merge it, so users donot get confused. Thanks

**Review by davepagurek — APPROVED** [review]

**Comment by davepagurek** [comment]
@all-contributors please add haroon10725 for docs
