### PR TITLE
Fix transforms in clip() by using shape system for primitives using manual method

### LINKED ISSUE #7903: [p5.js 2.0 Bug Report]: Transforms in `clip()` stopped working in 2.x
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

2.0.3

### Web browser and version

Firefox

### Operating system

MacOS

### Steps to reproduce this

The following code clips to a circle at the center of the screen:
```js
function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(220);
  noStroke()
  
  clip(() => {
    push()
    translate(width/2, height/2)
    circle(0, 0, 60)
    pop()
  })
  fill(0)
  rect(0, 0, 400, 400)
}
```

In 1.11.8 it looks like this:

Image

In 2.0.3 it looks like this, which is unexpected:

Image

Live: https://editor.p5js.org/davepagurek/sketches/IVloB6s76W

### PR DESCRIPTION
**Pull request by VANSH3104**
Resolves #7903

 Changes:

Modified ellipse() method in p5.Renderer2D to apply transforms during clipping
Used existing this.initialClipTransform (inverse of initial transform) stored in beginClip()
Applied correct matrix multiplication order: initialClipTransform.multiply(currentTransform)

 Screenshots of the change:

Screenshot 2025-11-06 at 1 09 33 PM

#### PR Checklist

- [x] `npm run lint` passes
- [ ] [Inline reference] is included / updated
- [x] [Unit tests] are included / updated

[Inline reference]: https://p5js.org/contribute/contributing_to_the_p5js_reference/
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

**Comment by VANSH3104** [comment]
@davepagurek I've implemented the manual fix for the ellipse() method and it's working correctly now!
I think moving to the class-based approach you suggested would be better long-term. Should I extend this manual fix to other primitives (rect, arc, etc.) first, or start working on migrating them to the shape system? and also drawshape function is useless i think its never call while clipping on or off

**Review by perminder-17 — CHANGES_REQUESTED** [review]
Also, your current solution applies to `ellipse` only? Do you think we need to add this solution in other shapes as well? `arc`/`quad`/`line` etc?

btw, thanks for working on this one.

**Comment by VANSH3104** [comment]
@perminder-17 yes it is only applicable for ellipse now I need to change for all too

**Comment by VANSH3104** [comment]
@perminder-17 I also have another idea class based approach also just want to discuss which one is better. I think This approach is temporary we need to find a perfect solution for that

**Comment by VANSH3104** [comment]
Screenshot 2025-11-12 at 1 32 57 AM
 it shows this @perminder-17

**Comment by perminder-17** [comment]
> @perminder-17 I also have another idea class based approach also just want to discuss which one is better. I think This approach is temporary we need to find a perfect solution for that

I saw @davepagurek's comment about the shape-system approach. It would be great long-term and would also unlock future tasks, but it feels like a fairly large refactor right now with higher regression risk. Since we already have the alternative approach working, how about we stick with that for now and plan to migrate the primitives into the shape drawing system later?

**Comment by perminder-17** [comment]
> Screenshot 2025-11-12 at 1 32 57 AM it shows this @perminder-17

I think this is not the expected behavior. 

I think you're storing inverse of initial clip transform into `beginClip()`, and multiplying with `currentTransform` , 

inside `endClip()` `clip()` is running with the `current transform`, and it's applying again i think. I am totally not sure with this but

Since, in the 1.x versions, it works something like: https://editor.p5js.org/aman12345/sketches/Csnrbz9BX , so would be great to test that too.

CC: @davepagurek for the confirmation on the approach as well as the bug if it's exist?

**Comment by VANSH3104** [comment]
@perminder-17  i think When we using scale(-1,1) inside clip(), the negative scale breaks the matrix calculations and makes the clipping region invisible. Basic clipping are working fine, but it give issue with complex transformations.

**Comment by VANSH3104** [comment]
Screenshot 2025-11-12 at 6 32 47 PM

@perminder-17  Now it work as expected it can handle -ve values also and i add condition and use absolute values to find the original position

File: src/core/p5.Renderer2D.js [hunk 1]
```diff
@@ -725,17 +726,39 @@ class Renderer2D extends Renderer {
...
+      const tempPath = new Path2D();
+      tempPath.ellipse(centerX, centerY, radiusX, radiusY, 0, 0, 2 * Math.PI);
+
+      const currentTransform = this.drawingContext.getTransform();
+      const initialClip = this.initialClipTransform;
+      if (currentTransform.a < 0 || currentTransform.d < 0) {
+        const fixedTransform = new DOMMatrix([
+          Math.abs(currentTransform.a), currentTransform.b,
+          currentTransform.c, Math.abs(currentTransform.d),
+          currentTransform.e, currentTransform.f
```
Comment (perminder-17) [inline src/core/p5.Renderer2D.js]: Looks like you're now forcing the geometry with negative transformations to make it positive. If the user actually wanted to mirror the orientation, it will actually cause problem to the geometry. I still think the problem is that our transformation is applied twice. 

I just tested code, and it looks like:

## When I apply scale(3) , the expected result is:

Screenshot from 2025-11-13 16-03-33

## The current behavior in the changes of this PR:
Screenshot from 2025-11-13 16-04-53

```js
function setup() {
  createCanvas(500, 500);
  background(240);

  clip(()=>{
    scale(3);
    ellipse(20, 40, 40, 40); 
  })
  fill(255, 80, 80);
  rect(0, 0, 500, 500);
}
```

this is the code I am using, Please ignore the calculations, I was just testing `scale()` and other transformations behaviour. 

`scale(2)` is equivalent to `scale(4)`, `scale(3)` is equivalent to `scale(9)` and I think this is the problem with the negetive stuff as well. 

As I was mentioning on previous comments, 
> I think you're storing inverse of initial clip transform into beginClip(), and multiplying with currentTransform , inside endClip() clip() is running with the current transform, and it's applying again i think. I am totally not sure with this but

Comment (VANSH3104) [reply src/core/p5.Renderer2D.js]: @perminder-17  Yes you re right  I test it I am working on the solution

Comment (perminder-17) [reply src/core/p5.Renderer2D.js]: > @perminder-17 Yes you re right I test it I am working on the solution

Feel free to reach out to me or @davepagurek if you face problems on the solution.

**Comment by VANSH3104** [comment]
@perminder-17 I implemented the clip transform fix we discussed. Following our conversation about the double transform issue where scale(2) was behaving like scale(4), I used the manual coordinate transformation approach. Instead of complex matrix math, I transform all coordinates to absolute screen space upfront, then reset the transform in endClip() before applying the clip. This ensures transforms are applied only once during path creation, not again during clipping.

**Comment by VANSH3104** [comment]
@perminder-17  am I on the right track ?

**Comment by VANSH3104** [comment]
@perminder-17   is this need any changes?

**Comment by VANSH3104** [comment]
@perminder-17 should i apply this on other shapes also ?

File: src/core/p5.Renderer2D.js [hunk 2]
```diff
@@ -725,17 +729,48 @@ class Renderer2D extends Renderer {
...
+    } else {
+      ctx.beginPath();
+      ctx.ellipse(centerX, centerY, radiusX, radiusY, 0, 0, 2 * Math.PI);
+      ctx.closePath();
+      if (doFill) {
+        ctx.fill();
+      }
+      if (doStroke) {
+        ctx.stroke();
+      }
```
Comment (perminder-17) [inline src/core/p5.Renderer2D.js]: Hi @VANSH3104 I am sorry for the delay in the response, I didn't got time to review this one. I just did some testing with this, the behaviour looks fine to me. 

But, you should implement it not in a manual way but something like storing `this.drawingContext.getTransform().inverse()` at the start of `clip()` and then multiply that with `this.drawingContext.getTransform()`. The exact way which you do in your first commit: https://github.com/processing/p5.js/pull/8236/commits/a5e15232e63fbfe087df0e1e0f444f8abeb0c77a

So, that commit will apply extra transforms internally, like you would be getting scale(2) ---> as scale(4). 

Fix for that would be:

in the `beginClip()` we should fetching the transformations.

```js
beginClip(){
//..
this._clipBaseTransform = this.drawingContext.getTransform();
//....
```

And in the `endClip()` we must set that. 
```js
    const saved = this.drawingContext.getTransform(); // here we will save the current transform to a variable.
    this.drawingContext.setTransform(this._clipBaseTransform); // While applying the clip, the canvas was given the same transform as _clipBaseTransform.
    this.drawingContext.clip(this.clipPath);   // Now the clipPath will apply on the correct space.                 
    this.drawingContext.setTransform(saved);  // In this puts your original/current transform back. Restoring that.
```

This could be the flow, no extra transform/rotations will be applied. Can you please check? Don't go with the manula logic, use the multiply logic which you used in your first commit. Thanks for the hlep.

Comment (VANSH3104) [reply src/core/p5.Renderer2D.js]: @perminder-17  thanks for the review i have implement yor suggestion of transform storing. I also test this and it work on all cases that we discussed previously

**Comment by VANSH3104** [comment]
@perminder-17  should i apply it to all shapes it look good from my side looking for your suggestion.

File: src/core/p5.Renderer2D.js [hunk 3]
```diff
@@ -725,17 +730,26 @@ class Renderer2D extends Renderer {
...
-    }
-    if (!this._clipping && doStroke) {
-      ctx.stroke();
+    if (this._clipping) {
+      const tempPath = new Path2D();
+      tempPath.ellipse(centerX, centerY, radiusX, radiusY, 0, 0, 2 * Math.PI);
+      const currentTransform = this.drawingContext.getTransform();
+      const ClipBaseTransform = this._clipBaseTransform.inverse();
+      const relativeTransform = ClipBaseTransform.multiply(currentTransform);
+      this.clipPath.addPath(tempPath, relativeTransform);
```
Comment (davepagurek) [inline src/core/p5.Renderer2D.js:747]: This looks right to me! The next step I think is to do this for the other shapes that directly draw to `ctx`.

**Comment by VANSH3104** [comment]
@davepagurek i add this to all other shapes also can you please check that too?

**Comment by VANSH3104** [comment]
@perminder-17 can you check this please

**Comment by VANSH3104** [comment]
@perminder-17 @davepagurek   could either of you please review this code please?

**Review by perminder-17 — APPROVED** [review]
Looks good to me! Thanks for your time and your work on this.

@davepagurek is there anything else you’d like in this PR? If not, I’ll go ahead and merge it?

**Comment by VANSH3104** [comment]
Hi @davepagurek , whenever you have a moment, I'd be grateful for your insights on this. Please let me know if you see anything that should be adjusted.

File: src/core/p5.Renderer2D.js [hunk 4]
```diff
@@ -668,7 +668,14 @@ class Renderer2D extends Renderer {
...
       radiusX = w / 2,
       radiusY = h / 2;
-
+    if (this._clipping) {
+      const tempPath = new Path2D();
+      tempPath.ellipse(centerX, centerY, radiusX, radiusY, 0, start, stop);
+      const currentTransform = this.drawingContext.getTransform();
+      const ClipBaseTransform = this._clipBaseTransform.inverse();
+      const relativeTransform = ClipBaseTransform.multiply(currentTransform);
+      this.clipPath.addPath(tempPath, relativeTransform);
```
Comment (davepagurek) [inline src/core/p5.Renderer2D.js:670]: Should we return early here like we do in the other cases?

File: src/core/p5.Renderer2D.js [hunk 5]
```diff
@@ -668,7 +668,14 @@ class Renderer2D extends Renderer {
       centerY = y + h / 2,
       radiusX = w / 2,
       radiusY = h / 2;
-
+    if (this._clipping) {
+      const tempPath = new Path2D();
+      tempPath.ellipse(centerX, centerY, radiusX, radiusY, 0, start, stop);
+      const currentTransform = this.drawingContext.getTransform();
+      const ClipBaseTransform = this._clipBaseTransform.inverse();
```
Comment (davepagurek) [inline src/core/p5.Renderer2D.js:668]: Super minor, but generally we only start class names with a capital letter. Could we rename this to `clipBaseTransform` to avoid confusion?

File: src/core/p5.Renderer2D.js [hunk 6]
```diff
@@ -801,17 +829,30 @@ class Renderer2D extends Renderer {
...
+      const relativeTransform = ClipBaseTransform.multiply(currentTransform);
+      this.clipPath.addPath(tempPath, relativeTransform);
+    } else{
+      ctx.beginPath();
+      ctx.moveTo(x1, y1);
+      ctx.lineTo(x2, y2);
+      ctx.lineTo(x3, y3);
+      ctx.lineTo(x4, y4);
+      ctx.closePath();
+      if (!this._clipping && doFill) {
```
Comment (davepagurek) [inline src/core/p5.Renderer2D.js:839]: We can take out the `!this._clipping` from this condition since we'll only be in the else block if this is the case

File: src/core/p5.Renderer2D.js [hunk 7]
```diff
@@ -754,28 +761,48 @@ class Renderer2D extends Renderer {
...
+      const tempPath = new Path2D();
+      const drawingContextWidth = this.drawingContext.lineWidth;
+      tempPath.arc(x, y, drawingContextWidth / 2, 0, constants.TWO_PI);
+      const currentTransform = this.drawingContext.getTransform();
+      const ClipBaseTransform = this._clipBaseTransform.inverse();
+      const relativeTransform = ClipBaseTransform.multiply(currentTransform);
+      this.clipPath.addPath(tempPath, relativeTransform);
+      return this;
+    }
     if (!this._clipping) {
```
Comment (davepagurek) [inline src/core/p5.Renderer2D.js:799]: We can clean up if statements like this, since we'll have returned early if we were clipping, making these checks no longer necessary

File: src/core/p5.Renderer2D.js (hunk 4 above)
Comment (VANSH3104) [reply src/core/p5.Renderer2D.js:670]: yes, we should return early here like in the other cases. I'll add return this; after the clipping logic to ensure consistency across all shape functions and prevent the normal drawing code from executing when clipping is active.

**Comment by VANSH3104** [comment]
@davepagurek Thanks for the thorough review! 
I've made all the requested changes: added early returns in all shape functions after clipping logic, fixed variable naming to clipBaseTransform (lowercase), removed unnecessary !this._clipping checks by wrapping normal drawing in else blocks, and applied this consistent pattern across all shapes (ellipse, arc, rect, triangle, quad, line, point).

File: src/core/p5.Renderer2D.js [hunk 8]
```diff
@@ -798,18 +800,14 @@ class Renderer2D extends Renderer {
...
-      const ClipBaseTransform = this._clipBaseTransform.inverse();
-      const relativeTransform = ClipBaseTransform.multiply(currentTransform);
+      const clipBaseTransform = this._clipBaseTransform.inverse();
+      const relativeTransform = clipBaseTransform.multiply(currentTransform);
       this.clipPath.addPath(tempPath, relativeTransform);
       return this;
-    }
-    if (!this._clipping) {
-      // swapping fill color to stroke and back after for correct point rendering
+    } else {
```
Comment (perminder-17) [inline src/core/p5.Renderer2D.js]: If we are returning early, do we still need to have an else block? We can take that else block and the PR would be good to go. Thanks so much for your patience and constant working on it.

**Comment by VANSH3104** [comment]
@perminder-17 Thank you for the review! It's my pleasure to complete the task. You are absolutely right I have now removed the else block from all shapes. Please let me know if there's anything else to address.

**Review by perminder-17 — APPROVED** [review]
Thanks for your work on this. Sorry for the delay in review, this looks good to me.
