### PR TITLE
fix(webgl): normalize nearly identical vertices before tessellation

### LINKED ISSUE #8186: [p5.js 2.0 Bug Report]: Tessellation of beginShape/endShape with multiple contours sometimes produces weird results
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

2.0.5, 1.11.10

### Web browser and version

Firefox, Chrome

### Operating system

MacOS

### Steps:
1. Use WebGL mode
2. Draw a shape with two intersecting contours
3. In one of the contours, make a vertex have one coordinate aaalmost equal to that coordinate of the previous, e.g. have x=1 and then x=1.00000001

The output of libtess is glitchy in this case:

<table>
<tr><th>Without a similar coordinate</th><th>With a similar coordinate</th></tr>
<tr>
<td>

Image

</td>
<td>

Image

</td>
</tr>
</table>

I debugged this and our vertices all look right going into libtess, and our GLU_TESS_COMBINE callback is working properly, so this is actually a bug within libtess. But libtess is a JS port of SGI C code from the 90s, I doubt they're actually going to fix this bug, and it's pretty subtle, so this feels like something we'll have to work around ourselves if we want to work around it at all.

### Workaround for users

Basically if they're drawing a bunch of points, they have to add a check like this before drawing the points:
```js
for (let i = 1; i < points.length; i++) {
  const prev = points[i-1]
  const next = points[i]
  if (Math.abs(prev.x - next.x) < 1e-6) next.x = prev.x
  if (Math.abs(prev.y - next.y) < 1e-6) next.y = prev.y
}
```

A fix for this probably would involve us doing that loop ourselves before tessellating a shape.

### Should we fix this at all?

It's unlikely that a user would manually create problematic coordinates like this, but it's a lot more likely to happen when drawing contours automatically sampled from a font with `font.textToContours()` (which is how I ran into this just now!) So if we do a fix, we can maybe consider it a fix for `textToContours` usage.

### Snippet:

```js
function setup() {
  createCanvas(400, 400, WEBGL);
}

function draw() {
  const contours = [
    [
      [-3.8642425537109375,-6.120738636363637,0],
      [3.2025188099254267,-6.120738636363637,0],
      [3.2025188099254267,-4.345170454545455,0],
      [-3.8642425537109375,-4.345170454545455,0],
      [-3.8642425537109375,-6.120738636363637,0],
    ],

    [
      [-1.8045834628018462,4.177556818181818,0],
      [-1.8045834628018462,-9.387784090909093,0],
      [0.29058699174360836,-9.387784090909093,0],
      ...(
        frameCount % 120 < 60
          ? [[0.2905869917436083,3.609374411367136,0]] // doesnt work
       // ? [[0.29058699174360836,3.609374411367136,0]] // works
          : []
      ),
      [0.31044303036623855,4.068235883781435,0],
      [0.38522861430307975,4.522728865422799,0],
      [0.548044378107245,4.941051136363637,0],
      [0.8364672032828204,5.2932224887960775,0],
      [1.2227602871981542,5.526988636363637,0],
      [1.6572258237923885,5.634502949876295,0],
      [2.101666537198154,5.669034090909091,0],
      [2.6695604948237173,5.633568761673102,0],
      [3.0249619917436084,5.5625,0],
      [3.4510983553799726,7.4446022727272725,0],
      [2.8568950819856695,7.613138889205699,0],
      [2.3751340936529037,7.676962586830456,0],
      [1.8892600236717598,7.693181792704519,0],
      [1.2922705720786674,7.649533731133848,0],
      [0.7080836288276859,7.519788939617751,0],
      [0.14854153719815422,7.311434659090909,0],
      [-0.38643934048179873,7.00959666478984,0],
      [-0.858113258144025,6.61653855366859,0],
      [-1.25415732643821,6.1484375,0],
      [-1.5108595282965422,5.697682732328092,0],
      [-1.6824918355513252,5.207533878495854,0],
      [-1.7762971052870198,4.695933154267308,0],
      [-1.8045834628018462,4.177556818181818,0],
    ]
  ]
  
  background('red')
  push()
  stroke(0)
  fill('#EEE')
  scale(15)
  beginShape()
  for (const contour of contours) {
    beginContour()
    for (const v of contour) {
      vertex(...v)
    }
    endContour()
  }
  endShape()
  
  stroke(0, 255, 0)
  strokeWeight(5)
  beginShape(POINTS)
  for (const contour of contours) {
    for (const v of contour) {
      vertex(...v)
    }
  }
  endShape()
  pop()
}
```

Live: https://editor.p5js.org/davepagurek/sketches/mvVHjXVjM

### PR DESCRIPTION
**Pull request by avinxshKD**
Resolves #8186

## Changes

This PR fixes tessellation artifacts that occur when drawing shapes with multiple contours where consecutive vertices have nearly identical coordinates (differing by ~1e-8 or similar small amounts). This commonly happens when using `font.textToContours()`.

- **Modified `_tesselateShape()` in `src/webgl/ShapeBuilder.js`:**
  - Added coordinate normalization loop before passing vertices to libtess tessellator
  - Consecutive vertices with coordinates within `1e-6` (epsilon) of each other are normalized to use the exact same value
  - Prevents numerical precision issues in libtess that cause glitchy rendering

- **Added visual test in `test/unit/visual/cases/webgl.js`:**
  - New visual test "Tessellation → Handles nearly identical consecutive vertices"
  - Easier for contributors to debug visually when issues arise

### Technical Background

This workaround addresses a numerical precision issue in libtess, which is a JavaScript port of SGI C code from the 1990s. When consecutive vertices have coordinates that are almost (but not exactly) equal, libtess produces glitchy tessellation output. This issue is particularly likely to occur with contours automatically sampled from fonts via `font.textToContours()`.

### Screenshots of the change

**Before:**
- Tessellation produces visual artifacts and incorrect geometry
- Referenced in issue #8186

**After (with this fix):**
- Clean tessellation with proper contour cutouts
- No visual artifacts

## PR Checklist

- [x] `npm run lint` passes
- [x] [Inline reference] is included / updated (N/A - internal fix, no API changes)
- [x] [Unit tests] are included / updated

[Inline reference]: https://p5js.org/contribute/contributing_to_the_p5js_reference/
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

File: src/webgl/ShapeBuilder.js [hunk 1]
```diff
@@ -313,6 +313,32 @@ export class ShapeBuilder {
...
+
+        if (Math.abs(currX - prevX) < epsilon) {
+          contour[i] = prevX;
+        }
+        if (Math.abs(currY - prevY) < epsilon) {
+          contour[i + 1] = prevY;
+        }
+        if (Math.abs(currZ - prevZ) < epsilon) {
+          contour[i + 2] = prevZ;
+        }
```
Comment (perminder-17) [inline src/webgl/ShapeBuilder.js]: Was there a reason for snapping the z coordinates as well? I don't think we need to do that for z?

File: test/unit/visual/cases/webgl.js [hunk 2]
```diff
@@ -693,4 +693,35 @@ visualSuite('WebGL', function() {
       screenshot();
     });
   });
+
+  visualSuite('Tessellation', function() {
```
Comment (perminder-17) [inline test/unit/visual/cases/webgl.js:1246]: The new visual test doesn’t actually cover this change. I see the same output before and after the patch. Please update the sketch to reproduce the bug which is fixed at your PR.

File: src/webgl/ShapeBuilder.js (hunk 1 above)
Comment (davepagurek) [reply src/webgl/ShapeBuilder.js]: I'm actually not 100% sure how libtess works internally, but maybe we could update my test sketch from the original issue to like, swap the x and z axes, and then draw it with a 90 degree rotation to see if we notice the same issue happening? If so, we probably need to do this for z too, otherwise maybe we don't

File: test/unit/visual/cases/webgl.js (hunk 2 above)
Comment (davepagurek) [reply test/unit/visual/cases/webgl.js:1246]: Worst case we can just use the exact same tests as in the original issue. I don't fully understand either why this case seems OK but not the one in the issue haha. I wonder if my numbers were bigger in the original and that causes more numerical precision issues

Comment (avinxshKD) [reply test/unit/visual/cases/webgl.js]: > Worst case we can just use the exact same tests as in the original issue. I don't fully understand either why this case seems OK but not the one in the issue haha. I wonder if my numbers were bigger in the original and that causes more numerical precision issues

Hello @perminder-17 @davepagurek thanks for the review

1.  **As you said that Visual test not showing the bug**
    Should I use the exact `textToContours()` example from issue #8186? 
  That one clearly shows the glitchy tessellation before the fix. I can add that as the visual test.

3. **Also about Z coordinates**
   I included Z because I thought it would be safer to normalize all three axes consistently. But you're right that the original issue only mentions X/Y coordinates. Should I:
   - Test if the issue happens with Z as Dave suggested (rotate the shape)?
   - Or remove Z normalization to keep the fix minimal?

Let me know and I'll update the PR accordingly and will also add similar changes to https://github.com/processing/p5.js/pull/8204

Comment (avinxshKD) [reply test/unit/visual/cases/webgl.js:1246]: > Worst case we can just use the exact same tests as in the original issue. I don't fully understand either why this case seems OK but not the one in the issue haha. I wonder if my numbers were bigger in the original and that causes more numerical precision issues


Hello @perminder-17 @davepagurek thanks for the review

1.  **As you said that Visual test not showing the bug**
    Should I use the exact `textToContours()` example from issue #8186? 
  That one clearly shows the glitchy tessellation before the fix. I can add that as the visual test.

3. **Also about Z coordinates**
   I included Z because I thought it would be safer to normalize all three axes consistently. But you're right that the original issue only mentions X/Y coordinates. Should I:
   - Test if the issue happens with Z as Dave suggested (rotate the shape)?
   - Or remove Z normalization to keep the fix minimal?

Let me know and I'll update the PR accordingly and will also add similar changes to https://github.com/processing/p5.js/pull/8204

Comment (perminder-17) [reply test/unit/visual/cases/webgl.js:1246]: > As you said that Visual test not showing the bug
Should I use the exact textToContours() example from issue https://github.com/processing/p5.js/issues/8186?
That one clearly shows the glitchy tessellation before the fix. I can add that as the visual test. 

For this one, maybe yes. you could add that in this scenario. 

> Test if the issue happens with Z as Dave suggested (rotate the shape)?

for this one, I tested it and I don't think we need to snap z coordinates.

**Comment by avinxshKD** [comment]
Hey @davepagurek @perminder-17, made the necessary changes. Please review whenever you get a chance.

File: test/unit/visual/cases/webgl.js [hunk 3]
```diff
@@ -692,6 +692,37 @@ visualSuite('WebGL', function() {
...
+      if (contours && contours.length > 0) {
+        p5.translate(-p5.width / 4, -p5.height / 4);
+        p5.beginShape();
+        for (let contourIdx = 0; contourIdx < contours.length; contourIdx++) {
+          const contour = contours[contourIdx];
+          if (contourIdx > 0) {
+            p5.beginContour();
+          }
+          for (let i = 0; i < contour.length; i++) {
+            p5.vertex(contour[i].x, contour[i].y, 0);
```
Comment (perminder-17) [inline test/unit/visual/cases/webgl.js]: I think this is still not reproducing the issue for which you're adding the visual tests.

Please use this sketch for the tests:

```js
function setup() {
  createCanvas(400, 400, WEBGL);
}

function draw() {
  const contours = [
    [
      [-3.8642425537109375,-6.120738636363637,0],
      [3.2025188099254267,-6.120738636363637,0],
      [3.2025188099254267,-4.345170454545455,0],
      [-3.8642425537109375,-4.345170454545455,0],
      [-3.8642425537109375,-6.120738636363637,0],
    ],

    [
      [-1.8045834628018462,4.177556818181818,0],
      [-1.8045834628018462,-9.387784090909093,0],
      [0.29058699174360836,-9.387784090909093,0],
      [[0.2905869917436083,3.609374411367136,0]] // doesnt work
      [0.31044303036623855,4.068235883781435,0],
      [0.38522861430307975,4.522728865422799,0],
      [0.548044378107245,4.941051136363637,0],
      [0.8364672032828204,5.2932224887960775,0],
      [1.2227602871981542,5.526988636363637,0],
      [1.6572258237923885,5.634502949876295,0],
      [2.101666537198154,5.669034090909091,0],
      [2.6695604948237173,5.633568761673102,0],
      [3.0249619917436084,5.5625,0],
      [3.4510983553799726,7.4446022727272725,0],
      [2.8568950819856695,7.613138889205699,0],
      [2.3751340936529037,7.676962586830456,0],
      [1.8892600236717598,7.693181792704519,0],
      [1.2922705720786674,7.649533731133848,0],
      [0.7080836288276859,7.519788939617751,0],
      [0.14854153719815422,7.311434659090909,0],
      [-0.38643934048179873,7.00959666478984,0],
      [-0.858113258144025,6.61653855366859,0],
      [-1.25415732643821,6.1484375,0],
      [-1.5108595282965422,5.697682732328092,0],
      [-1.6824918355513252,5.207533878495854,0],
      [-1.7762971052870198,4.695933154267308,0],
      [-1.8045834628018462,4.177556818181818,0],
    ]
  ]
  
  background('red')
  push()
  stroke(0)
  fill('#EEE')
  scale(15)
  beginShape()
  for (const contour of contours) {
    beginContour()
    for (const v of contour) {
      vertex(...v)
    }
    endContour()
  }
  endShape()
  
  stroke(0, 255, 0)
  strokeWeight(5)
  beginShape(POINTS)
  for (const contour of contours) {
    for (const v of contour) {
      vertex(...v)
    }
  }
  endShape()
  pop()
}
```

**Comment by avinxshKD** [comment]
@perminder-17 Sorry for the delay, was busy with exams. I've now updated the test to match your sketch exactly. thanks

**Comment by avinxshKD** [comment]
hey @perminder-17 , I ran `npm test` locally and the visual test passes. Also pushed the generated screenshot and metadata.json file. thanks

**Comment by perminder-17** [comment]
Okay, there's some conflicts, can you take a look once?

**Comment by avinxshKD** [comment]
@perminder-17 @davepagurek, Pls take a look, thanks

**Comment by avinxshKD** [comment]
Thanks @perminder-17 for tuning in through the whole PR , happy to work on more
