### PR TITLE
Removes invalid website inconsolata reference

### LINKED ISSUE #5380: nf and nfs examples not working
#### Most appropriate sub-area of p5.js?

- [ ] Accessibility (Web Accessibility)
- [ ] Build tools and processes
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Friendly error system
- [ ] Image
- [ ] IO (Input/Output)
- [ ] Localization
- [ ] Math
- [ ] Unit Testing
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [X] Other (specify if possible)
Documentation

#### Details about the bug:

- p5.js version: main branch
- Web browser and version: chrome 92.0.4515.131
- Operating System: MacOSX
- Steps to reproduce this:

Open https://p5js.org/reference/#/p5/nf and https://p5js.org/reference/#/p5/nfs

Because fonts/inconsolata files are returning 404 on the p5js.org domain, the examples are not loaded.

### PR DESCRIPTION
**Pull request by guilhermesilveira**
Resolves #5380

 Changes:
To show nf and nfs working there is no need of an extra font. Instead of relying on the deployment of a folder with extra files to the webserver I simply removed the need for the inconsolata font file.

The documentation string for both methods were also updated with double returns to better readability.

 Screenshots of the change:

#### PR Checklist

- [X] [Inline documentation] is included / updated

### CODE REVIEW

File: src/utilities/string_functions.js [hunk 1]
```diff
@@ -149,18 +152,13 @@ p5.prototype.matchAll = function(str, reg) {
...
- * }
  * function setup() {
  *   background(200);
  *   let num1 = 321;
  *   let num2 = -1321;
  *
  *   noStroke();
  *   fill(0);
- *   textFont(myFont);
  *   textSize(22);
```
Comment (outofambit) [inline src/utilities/string_functions.js:162]:
```suggestion
 *   textSize(16);
```

File: src/utilities/string_functions.js [hunk 2]
```diff
@@ -398,18 +401,13 @@ function addNfp(num) {
...
```
Comment (outofambit) [inline src/utilities/string_functions.js:411]:
```suggestion
 *   textSize(16);
```

**Comment by outofambit** [comment]
i went ahead and made that change @limzykenneth . thank you @guilhermesilveira !
