### PR TITLE
Fix inline anonymous functions causing a parsing error in p5.strands callbacks

### LINKED ISSUE #7955: [p5.js 2.0 Bug Report]: p5.strands callbacks don't work with inline anonymous non-arrow functions
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [x] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [ ] Other (specify if possible)

### p5.js version

2.0.3

### Web browser and version

Firefox

### Operating system

MacOS

### Steps:
1. Take a p5.strands example (e.g. the first on here: https://beta.p5js.org/reference/p5/basematerialshader/)
2. Change the arrow function to a `function() { ... }`

The code stops working.

### Snippet:

```js
let myShader;

function setup() {
  createCanvas(200, 200, WEBGL);
  // Works:
  // myShader = baseMaterialShader().modify(() => {
  
  // Doesn't work:
  myShader = baseMaterialShader().modify(function() {
    let time = uniformFloat(() => millis());
    getWorldInputs((inputs) => {
      inputs.position.y +=
        20 * sin(time * 0.001 + inputs.position.x * 0.05);
      return inputs;
    });
  });
}

function draw() {
  background(255);
  shader(myShader);
  lights();
  noStroke();
  fill('red');
  sphere(50);
}
```

Live: https://editor.p5js.org/davepagurek/sketches/Xla02SjFQ

### PR DESCRIPTION
**Pull request by nking07049925**
Resolves #7955

 Changes:

WebGL `ShaderGenerator.js`
- Wraps function source string in round brackets to prevent issues with [acorn](https://github.com/acornjs/acorn) parsing top level function statements

Unit Tests
- Adds a unit test to `p5.Shader` for an anonymous function being passed into the shader

#### Screenshots of the change

Example from the issue running locally with no errors
image

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Unit tests] are included / updated

[Inline reference]: https://p5js.org/contribute/contributing_to_the_p5js_reference/
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

### CODE REVIEW

File: src/webgl/ShaderGenerator.js [hunk 1]
```diff
@@ -19,7 +19,7 @@ function shadergenerator(p5, fn) {
     if (shaderModifier instanceof Function) {
       let generatorFunction;
       if (options.parser) {
-        const sourceString = shaderModifier.toString()
+        const sourceString = `(${shaderModifier.toString()})`;
```
Comment (davepagurek) [inline src/webgl/ShaderGenerator.js:24]: Do you mind adding a comment here to explain to other contributors why the brackets are necessary?

**Review by davepagurek — COMMENTED** [review]
Thanks for adding this, and the test as well! Just one minor comment about leaving some context for the change behind.

File: src/webgl/ShaderGenerator.js (hunk 1 above)
Comment (nking07049925) [reply src/webgl/ShaderGenerator.js:24]: Would something like this work?
```
// #7955 Wrap function declaration code in brackets so anonymous functions are not top level statements, which causes an error in acorn when parsing
```

Comment (davepagurek) [reply src/webgl/ShaderGenerator.js:24]: looks great, thanks!

Comment (nking07049925) [reply src/webgl/ShaderGenerator.js:24]: Nice! I will be able to make a commit later today

**Comment by davepagurek** [comment]
@all-contributors please add @nking07049925 for code
