### PR TITLE
fix: prevent browser freeze when tessellating >50k vertices (#8219 )

### LINKED ISSUE #8219: Browser freeze when creating >65k vertices in draw() loop (no validation or warning)
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [x] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] p5.strands
- [x] WebGL
- [ ] DevOps, Build process, Unit testing
- [ ] Internationalization (i18n)
- [x] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.11.10 (also tested on 2.0.5,issue exists in all versions)

### Web browser and version

all browser

### Operating system

windows 11

### Steps:
1. Paste the code below into the p5.js web editor (editor.p5js.org)
2. Click "Play"
3. Wait 1-2 seconds

### Snippet:

```js
function setup() {
  createCanvas(400, 400, WEBGL);
}

function draw() {
  background(200);
  beginShape();
  
  // Creating 100,000 vertices (exceeds 65k limit)
  for (let i = 0; i < 100000; i++) {
    vertex(random(-200, 200), random(-200, 200), random(-200, 200));
  }
  
  endShape();
}

```

### PR DESCRIPTION
**Pull request by Nixxx19**
### Summary
- **Adds a one‑time confirmation prompt** before tessellating very large `TESS` shapes (>50,000 vertices) to avoid browser freezes in `libtess` during `_triangulate()`.
- **Cancel**: skips tessellation and **draws nothing** for that shape (no TRIANGLE_FAN fallback), keeping behavior explicit and predictable.
- **OK**: remembers the choice for the lifetime of the renderer via `_largeTessellationAcknowledged` and tessellates normally without prompting again.
- **Respects `p5.disableFriendlyErrors` / minified builds**: when friendly errors are disabled, tessellation always runs with no prompt.

### Tests
- Adds / updates WebGL unit tests in `test/unit/webgl/p5.RendererGL.js` to cover:
  - Prompting once for large shapes and including the vertex count in the message.
  - Skipping tessellation entirely on cancel (no TRIANGLE_FAN fallback).
  - Only prompting once per renderer when the user approves.
  - Skipping the prompt when `p5.disableFriendlyErrors` is `true`.
  - Normal tessellation behavior for shapes below the 50k‑vertex threshold.

### Screenshot
Screenshot 2026-03-17 at 4 20 38 PM

### PR Checklist
- [x] `npm run lint` passes
- [ ] Inline reference is included / updated (not applicable – bug fix only)
- [x] Unit tests are included / updated

### CODE REVIEW

**Comment by davepagurek** [comment]
Thanks for working on this! As this is into the `main` branch, we'll want another PR after this making similar changes into the `dev-2.0` branch, where p5 2.x is developed. The code looks like it could largely be the same (but you'll likely want to manually change it on the new base because so much has changed between the branches, merging/rebasing won't be easy), and also how mocking works in tests is a little different as 2.x switched to using vitest.

File: test/unit/webgl/p5.RendererGL.js [hunk 1]
```diff
@@ -1686,6 +1686,115 @@ suite('p5.RendererGL', function() {
...
+
+      assert.equal(confirmStub.callCount, 1, 'confirm should not be called again after acknowledgement');
+
+      confirmStub.restore();
+      done();
+    });
+
+    test('TESS mode skips prompt when p5.disableFriendlyErrors is true', function(done) {
+      var renderer = myp5.createCanvas(10, 10, myp5.WEBGL);
+      var confirmStub = sinon.stub(window, 'confirm').returns(false);
```
Comment (davepagurek) [inline test/unit/webgl/p5.RendererGL.js:1750]: It looks like tests are currently failing here:

```
   2) Graphics
       p5.Graphics.resizeCanvas
         Rendering
           p5.prototype.resizeCanvas
             p5.Framebuffer
               sizing
                 p5.RendererGL
                   beginShape() in WEBGL mode
                     TESS mode skips prompt when p5.disableFriendlyErrors is true:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

Does this test also take a while locally?

Comment (Nixxx19) [reply test/unit/webgl/p5.RendererGL.js:1750]: sorry about that! the test was timing out because when `p5.disableFriendlyErrors` is true, the prompt is skipped and tessellation actually runs on 60k vertices, which is the freeze we're trying to guard against. fixed by stubbing `_tesselateShape` in the tests that would otherwise trigger real tessellation. also added an assertion that `_tesselateShape` is called in the `disableFriendlyErrors` case to confirm the code path is exercised. applied the same stub to the "only prompts once" test as well since confirm returns true there.

**Comment by Nixxx19** [comment]
hey @davepagurek, opened the dev-2.0 pr #8729! tests rewritten in vitest syntax and the guard adapted to the new ShapeBuilder structure in 2.x. happy to adjust if anything needs tweaking!

**Comment by davepagurek** [comment]
Thanks @Nixxx19, looks good now!
