### PR TITLE
Fix rotation properties being in degrees irrespective of angleMode

### LINKED ISSUE #6565: Multiple reference to non-existant constant `POLYGON` in Renderer2D
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

1.8.0

### Web browser and version

*

### Operating System

*

### Steps to reproduce this

There are multiple [references](https://github.com/processing/p5.js/blob/v1.8.0/src/core/p5.Renderer2D.js#L857) to `constants.POLYGON` in `src/core/p5.Renderer2D.js` but in `src/core/constants.js` where all constants came from, there is no `POLYGON` defined.

I don't know if it has affected anything (haven't looked into it) but if so it probably is very subtle as this has been around for a very very long time without notice. I would suggest anyone wanting to address this look into whether this problem has an effect or not first.

### PR DESCRIPTION
**Pull request by SlightlyEpic**
Resolves #6565

 Changes:  
 
1. Fixing the incorrectly lowercased reference to `constants.RADIANS` at
https://github.com/processing/p5.js/blob/773eb0d4aaee30238b15d53c955272ac6c53d806/src/events/acceleration.js#L622
This was also casuing rotation and pRotation properties being in degrees irrespective of the `_angleMode`.

2. Changes to `_handleMotion` function were made to make it work with both degree and radian values.

3. Changes in unit tests related to rotation were made as they expected degree values despite the default mode being radian.

4. The `angleMode` method in math/trigonometry.js was also changed to update pRotation properties when the mode is changed, this is needed because otherwise the units of rotation and pRotation could end up different, which may cause the `deviceTurned` event to fire incorrectly.

#### PR Checklist
- [x] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

### CODE REVIEW

File: src/events/acceleration.js [hunk 1]
```diff
@@ -619,14 +619,14 @@ p5.prototype.setShakeThreshold = function(val) {
...
+  let multiplier = 1;
+  if (this._angleMode === constants.RADIANS) {
+    multiplier = constants.PI / 180.0;
   }
-  this._setProperty('rotationX', e.beta);
-  this._setProperty('rotationY', e.gamma);
-  this._setProperty('rotationZ', e.alpha);
+  this._setProperty('rotationX', e.beta * multiplier);
+  this._setProperty('rotationY', e.gamma * multiplier);
+  this._setProperty('rotationZ', e.alpha * multiplier);
```
Comment (limzykenneth) [inline src/events/acceleration.js:629]: There is an internal method to convert angles, can you see if you can use that to simplify the implementation instead? https://github.com/processing/p5.js/blob/main/src/math/trigonometry.js#L437

Comment (SlightlyEpic) [reply src/events/acceleration.js]: Ive added a new internal method, similar to the one you pointed out which converts from degrees to the current angle mode unit (since that one was missing and was needed here).
Another simplification i made is that in the `_handleMotion` method, instead of switching the equations based on angle mode, rotation properties are now converted into degrees beforehand and all calculations are done in degrees.

**Comment by SlightlyEpic** [comment]
Ive added a new internal method, similar to the one you pointed out which converts from degrees to the current angle mode unit (since that one was missing and was needed here).
Another simplification i made is that in the `_handleMotion` method, instead of switching the equations based on angle mode, rotation properties are now converted into degrees beforehand and all calculations are done in degrees.

**Comment by limzykenneth** [comment]
Looks good. Thanks!
